'use client';
import {useState} from 'react';
import {api} from '@/lib/browser';
import {Field,type Row} from './Forms';
import type {Run} from './Workspace';
export default function AdminPanel({data,loading,busy,run,onRefresh,onNotice}:{data:Row|null;loading:boolean;busy:boolean;run:Run;onRefresh:()=>void;onNotice:(s:string)=>void}) {
 const [tab,setTab]=useState('pending'),[query,setQuery]=useState('');
 const profiles:Row[]=data?.profiles||[],cases:Row[]=data?.cases||[];
 const matches=(x:Row)=>[x.name,x.title,x.city,x.license].join(' ').toLowerCase().includes(query.toLowerCase());
 const people=profiles.filter(x=>matches(x)&&(tab!=='pending'||x.verification==='pending'));
 const matters=cases.filter(x=>matches(x)&&(tab!=='pending'||x.status==='review'));
 const submit=(path:string,payload:Row)=>void run(async()=>{await api(path,'PATCH',payload);onRefresh();onNotice('La decisión quedó registrada.');});
 return <><div className="page-heading"><div><span className="overline">ADMINISTRACIÓN · ACCESO PRIVADO</span><h1>Cuidemos este espacio</h1><p>Revisa cada solicitud y explica el siguiente paso.</p></div><button className="button outline small" onClick={onRefresh} disabled={busy}>Actualizar</button></div>
 <div className="inline-actions" style={{flexWrap:'wrap',marginBottom:24}}>{[['pending',`Pendientes (${profiles.filter(x=>x.verification==='pending').length+cases.filter(x=>x.status==='review').length})`],['professionals','Profesionales'],['cases','Casos'],['history','Historial'],['rules','Criterios e IA']].map(([id,label])=><button key={id} className={'button small '+(tab===id?'':'outline')} onClick={()=>setTab(id)}>{label}</button>)}</div>
 {['pending','professionals','cases'].includes(tab)&&<Field label="Buscar por nombre, título, ciudad o tarjeta profesional"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Encuentra una solicitud…"/></Field>}
 {loading&&<p role="status">Cargando solicitudes…</p>}
 {['pending','professionals'].includes(tab)&&<section><h2>Profesionales</h2>{people.map(p=><article className="panel" key={p.id}><h3>{p.name}</h3><p>T.P. {p.license||'No informada'} · {p.city} · {p.verification==='verified'?'Verificado':p.verification==='pending'?'Pendiente':'Requiere ajustes / acceso suspendido'}</p><p>{p.bio}</p><p>{p.specialties?.join(' · ')}</p>{p.verification_note&&<p className="notice-panel">Última revisión: {p.verification_note}</p>}<form className="form-stack" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);submit('admin/'+p.id,{verification:f.get('decision'),note:f.get('note')});}}><Field label="Decisión"><select name="decision" required defaultValue=""><option value="" disabled>Selecciona después de revisar</option><option value="verified">Aprobar habilitación profesional</option><option value="rejected">Pedir ajustes / rechazar / suspender</option></select></Field><Field label="Comprobación y motivo (visible para el profesional)"><textarea name="note" required minLength={20} maxLength={2000} placeholder="Fuente oficial, fecha, identidad cotejada, resultado y qué debe corregir si corresponde."/></Field><label className="checkbox-line"><input type="checkbox" required/>Comprobé la información que sustenta esta decisión.</label><button className="button small" disabled={busy}>Registrar decisión</button></form></article>)}{!loading&&!people.length&&<p className="notice-panel">No hay profesionales en esta vista.</p>}</section>}
 {['pending','cases'].includes(tab)&&<section><h2>Publicaciones de casos</h2>{matters.map(c=><article className="panel" key={c.id}><div className="split"><h3>{c.title}</h3><span className="tag">{c.status==='review'?'Pendiente':'Publicado'}</span></div><p>{c.category} · {c.city} · {c.service}</p><p className="preserve">{c.public_summary}</p><p className="microcopy">Esta es la presentación para el marketplace. Los borradores y documentos privados no se muestran aquí.</p><form className="form-stack" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);submit('admin/cases/'+c.id,{decision:f.get('decision'),note:f.get('note'),version:c.updated_at});}}><Field label="Decisión"><select name="decision" required defaultValue=""><option value="" disabled>Selecciona después de revisar</option>{c.status==='review'?<><option value="approved">Aprobar publicación</option><option value="changes_requested">Solicitar ajustes</option><option value="rejected">Rechazar publicación</option></>:<option value="removed">Retirar del marketplace</option>}</select></Field><Field label="Motivo y próximos pasos (visible para el cliente)"><textarea name="note" required minLength={20} maxLength={2000} placeholder="Explica qué comprobaste o qué debe corregirse para publicar."/></Field><button className="button small" disabled={busy}>Registrar decisión</button></form></article>)}{!loading&&!matters.length&&<p className="notice-panel">No hay publicaciones en esta vista. Los borradores aparecen cuando el cliente los envía a revisión.</p>}</section>}
 {tab==='history'&&<section><h2>Historial de decisiones</h2><p>Últimas 50 acciones. Cada registro conserva responsable, fecha, motivo y referencia.</p>{data?.audit?.map((a:Row)=><article className="panel" key={a.id}><b>{a.action}</b><p>{new Date(a.created_at).toLocaleString('es-CO')}</p><p className="microcopy" style={{overflowWrap:'anywhere'}}>Responsable: {a.actor_id} · Referencia: {a.target_id}</p><p className="preserve" style={{overflowWrap:'anywhere'}}>{a.note}</p></article>)}{!data?.audit?.length&&<p>Todavía no hay decisiones registradas.</p>}</section>}
 {tab==='rules'&&<section className="panel"><span className="tag">Revisión manual activa</span><h2>Qué revisamos</h2><ul><li>Profesionales: identidad y habilitación respaldadas por una fuente oficial, con fecha y evidencia.</li><li>Casos: presentación comprensible, sin datos personales expuestos, spam ni contenido abusivo. La aprobación permite publicarlo; no certifica su viabilidad jurídica.</li><li>Correcciones: motivo claro y posibilidad de reenviar. Las decisiones quedan en el historial.</li></ul><h3>Próxima etapa: asistencia por IA</h3><p>La IA de moderación aún no está conectada. Podrá proponer alertas y recomendaciones con evidencia; el administrador conservará la decisión final. No se ejecutan aprobaciones automáticas.</p></section>}
 </>;
}
