'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,Check,FileText,FolderOpen,LockKeyhole,Plus,Trash2,X} from 'lucide-react';
import {categories,services,caseSchema} from '@/lib/shared';
import {documentKinds,draftStore,fileProblem,suggestKind,type IntakeFile} from '@/lib/intake';
const headings=['Todo empieza por aquí.','Vamos a ponerle orden.','¿Qué te gustaría hacer ahora?','Así empieza tu espacio.'];
export default function CaseIntake({onClose,onReady}:{onClose:()=>void;onReady:(data:Record<string,string>)=>void}){
 const ref=useRef<HTMLDialogElement>(null),input=useRef<HTMLInputElement>(null);
 const [step,setStep]=useState(0),[files,setFiles]=useState<IntakeFile[]>([]),[data,setData]=useState<Record<string,string>>({title:'',description:'',category:'Otro',city:'',service:services[0],urgency:'normal',public_summary:''}),[error,setError]=useState(''),[busy,setBusy]=useState(false),[ready,setReady]=useState(false);
 useEffect(()=>{ref.current?.showModal();void draftStore('read').then(d=>{if(d&&!d.caseId){setData(d.data);setFiles(d.files);}setReady(true);}).catch(()=>setReady(true));},[]);
 function update(key:string,value:string){setData(d=>({...d,[key]:value}));}
 async function save(){await draftStore('write',{data,files,updated:Date.now()});}
 async function leave(){setBusy(true);try{await save();onClose();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function add(list:File[]){setError('');if(files.length+list.length>30){setError('Puedes reunir hasta 30 archivos.');return;}const problem=list.map(fileProblem).find(Boolean);if(problem){setError(problem);return;}setBusy(true);try{const added=await Promise.all(list.map(async file=>{const text=/\.txt$/i.test(file.name)?(await file.text()).slice(0,10000):'';return {id:crypto.randomUUID(),file,kind:suggestKind(file.name,text)};}));setFiles(f=>[...f,...added]);}finally{setBusy(false);}}
 async function next(){setError('');if(step===0&&!files.length&&data.description.trim().length<30){setError('Añade un documento o cuéntanos un poco más: al menos 30 caracteres.');return;}if(step===2){const parsed=caseSchema.safeParse(data);if(!parsed.success){setError('Completa el nombre (8 caracteres), la ciudad y un relato de al menos 30 caracteres.');return;}}setBusy(true);try{await save();if(step===3){onReady(data);}else setStep(s=>s+1);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <dialog ref={ref} className="intake-dialog" aria-labelledby="intake-title" onCancel={e=>{e.preventDefault();void leave();}}><div className="intake-layout"><aside className="intake-aside"><a className="brand" href="#" onClick={e=>{e.preventDefault();void leave();}}>Lex<span>Market</span><span className="brand-dot">.</span></a><div><span className="eyebrow">UN PASO A LA VEZ</span><h2>Lo que tienes.<br/>Lo que sigue.</h2><p>Un lugar para reunir tu material y encontrar a quién confiarle el siguiente paso.</p></div><img src="/lexmarket-journey.webp" alt="Papeles y una carpeta conectados por un camino lila hacia una puerta abierta"/><p className="intake-private"><LockKeyhole size={15}/> Por ahora, todo se queda en este dispositivo.</p></aside><main className="intake-main"><header><span>{['Tu punto de partida','Tu material','El siguiente paso','Tu espacio'][step]} · {step+1} de 4</span><button className="icon-button" onClick={()=>void leave()} aria-label="Guardar borrador en este dispositivo y salir" disabled={busy}><X/></button></header><div className="intake-progress" aria-label={`Paso ${step+1} de 4`}>{headings.map((h,i)=><span key={h} className={i<=step?'active':''}/>)}</div><section className="intake-content" key={step}><h1 id="intake-title">{headings[step]}</h1>
 {step===0&&<><p>Puedes traer un escrito, una conversación, los documentos que has reunido… o empezar contándonos.</p><div className="intake-drop" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();void add(Array.from(e.dataTransfer.files));}}><FolderOpen size={38}/><h3>Hazle espacio a tus documentos</h3><p>Arrástralos aquí o selecciónalos desde tu dispositivo.</p><button className="button outline" disabled={busy} onClick={()=>input.current?.click()}><Plus size={18}/> Elegir archivos</button><small>PDF, Word (.docx) o texto · hasta 10 MB por archivo</small></div>{files.length>0&&<p className="intake-selected"><Check size={17}/>{files.length} archivo{files.length!==1?'s':''} seleccionado{files.length!==1?'s':''}. Los organizamos en el siguiente paso.</p>}<label className="field"><span>También puedes contarnos o pegar tus notas</span><textarea rows={4} maxLength={40000} value={data.description} onChange={e=>update('description',e.target.value)} placeholder="Lo que pasó, lo que ya has hecho, lo que te gustaría resolver…"/></label></>}
 {step===1&&<><p>Estas etiquetas son sugerencias por el nombre del archivo y, en los TXT, por su texto. Puedes cambiarlas. Los PDF y Word se procesan después de guardarlos en tu cuenta.</p><div className="intake-files">{files.map(f=><article key={f.id}><FileText size={23}/><div><b>{f.file.name}</b><small>{(f.file.size/1024/1024).toFixed(2)} MB</small><select aria-label={'Tipo de '+f.file.name} value={f.kind} onChange={e=>setFiles(a=>a.map(v=>v.id===f.id?{...v,kind:e.target.value}:v))}>{documentKinds.map(k=><option key={k}>{k}</option>)}</select></div><button className="icon-button" aria-label={'Quitar '+f.file.name} onClick={()=>setFiles(a=>a.filter(v=>v.id!==f.id))}><Trash2 size={17}/></button></article>)}</div>{!files.length&&<div className="intake-note"><FileText/><p>Tus palabras también son un buen punto de partida. Puedes añadir documentos más adelante.</p></div>}<button className="text-button" onClick={()=>input.current?.click()} disabled={busy}><Plus size={17}/> Añadir otro archivo</button></>}
 {step===2&&<><p>Elige lo que necesitas del profesional. Podrás ajustarlo después.</p><div className="intake-choices">{services.map((s,i)=><button key={s} className={data.service===s?'selected':''} aria-pressed={data.service===s} onClick={()=>update('service',s)}><span>0{i+1}</span>{s}{data.service===s&&<Check size={17}/>}</button>)}</div><div className="form-grid"><label className="field"><span>¿Dónde ocurre?</span><input maxLength={80} placeholder="Ciudad o municipio" value={data.city} onChange={e=>update('city',e.target.value)}/></label><label className="field"><span>¿Con qué se relaciona?</span><select value={data.category} onChange={e=>update('category',e.target.value)}>{categories.map(c=><option key={c}>{c}</option>)}</select></label></div><label className="field"><span>Un nombre para encontrarlo fácilmente</span><input maxLength={120} placeholder="Por ejemplo: mi reclamación laboral" value={data.title} onChange={e=>update('title',e.target.value)}/></label><label className="field"><span>Lo que debería entender quien te acompañe</span><textarea rows={4} maxLength={40000} value={data.description} onChange={e=>update('description',e.target.value)} placeholder="Cuéntanos brevemente qué sucede y qué has preparado."/></label><label className="field"><span>¿Qué tan pronto necesitas avanzar?</span><select value={data.urgency} onChange={e=>update('urgency',e.target.value)}><option value="normal">Puedo revisar las opciones con calma</option><option value="soon">Me gustaría avanzar pronto</option><option value="urgent">Tengo una urgencia o un plazo</option></select></label>{data.urgency==='urgent'&&<p className="microcopy">Busca atención directa si tienes un vencimiento. Aquí no se suspenden plazos ni se garantiza respuesta inmediata.</p>}</>}
 {step===3&&<><p>Primero lo guardamos para ti. Compartirlo con abogados será una decisión aparte.</p><article className="intake-preview"><span className="tag">BORRADOR PRIVADO</span><h2>{data.title}</h2><p>{data.city} · {data.category}</p><strong>{data.service}</strong><p className="intake-excerpt">{data.description}</p><div className="intake-preview-bottom"><FileText size={18}/>{files.length} documentos preparados</div></article><div className="intake-note"><LockKeyhole size={24}/><p>Al continuar, crea tu cuenta o entra a la que ya tienes. Guardaremos tu caso y subiremos los archivos a tu espacio privado. Tú eliges qué resumen publicar y a quién dar acceso.</p></div></>}
 {error&&<p role="alert" className="intake-error">{error}</p>}</section><footer className="intake-footer"><button className="text-button" onClick={()=>step?setStep(s=>s-1):void leave()} disabled={busy}><ArrowLeft size={17}/>{step?'Atrás':'Guardar y salir'}</button><button className="button" disabled={busy||!ready} onClick={()=>void next()}>{busy?'Un momento…':step===3?'Guardar mi espacio':'Continuar'}<ArrowRight size={17}/></button></footer></main></div><input hidden ref={input} type="file" multiple accept=".pdf,.docx,.txt" onChange={e=>{void add(Array.from(e.target.files||[]));e.target.value='';}}/></dialog>;
}
