'use client';
import { useEffect, useState } from 'react';
import { ArrowLeft, ArrowRight, Check, Download, FileText, LockKeyhole, MessageCircle, Plus, Send, ShieldCheck, Sparkles, Star, Trash2 } from 'lucide-react';
import { api, browserDB } from '@/lib/browser';
import { statusLabels } from '@/lib/shared';
import { CaseForm, Field, Modal, UploadBox, type Row } from './Forms';
import { Empty, type WorkProps } from './Workspace';
const money=(n:number)=>new Intl.NumberFormat('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:0}).format(n);
const date=(s:string)=>new Date(s).toLocaleString('es-CO',{dateStyle:'medium',timeStyle:'short'});
export default function CaseView(props:WorkProps&{id:string;onBack:()=>void}) {
 const {id,run,busy,onNotice,session}=props;
 const [data,setData]=useState<Row|null>(null),[loadError,setLoadError]=useState(''),[tab,setTab]=useState('overview'),[modal,setModal]=useState(''),[selected,setSelected]=useState<Row|null>(null),[professional,setProfessional]=useState<Row|null>(null),[lawyerId,setLawyerId]=useState(''),[uploadProgress,setUploadProgress]=useState('');
 async function refresh(){setData(await api('cases/'+id));}
 useEffect(()=>{let active=true;api('cases/'+id).then(d=>{if(active)setData(d);}).catch(e=>{if(active)setLoadError(e.message);});const timer=setInterval(()=>{if(document.visibilityState==='visible')api('cases/'+id).then(d=>{if(active)setData(d);}).catch(()=>{});},15000);return ()=>{active=false;clearInterval(timer);};},[id]);
 const c=data?.case,owner=!!data?.owner,hasPrivate=!!data?.private;
 async function action(path:string,payload:Row={},method='POST'){await api('cases/'+id+'/'+path,method,payload);await refresh();setModal('');}
 function name(lid:string){return data?.professionals.find((p:Row)=>p.id===lid)?.name||'Profesional';}
 async function showProfessional(lid:string){setProfessional(await api('professionals/'+lid));setModal('professional');}
 async function files(list:File[]){if(!list.length)return;await run(async()=>{const failed:string[]=[];for(let i=0;i<list.length;i++){setUploadProgress(`${i+1} de ${list.length}: ${list[i].name}`);try{const form=new FormData();form.append('file',list[i]);await api('cases/'+id+'/documents','POST',form);}catch(e){failed.push(list[i].name+': '+(e instanceof Error?e.message:'No se pudo subir'));}}setUploadProgress('');await refresh();if(failed.length)throw new Error(failed.join(' · '));onNotice('Archivos recibidos. Los estamos preparando para que puedas usarlos en tu caso.');});}
 async function download(d:Row){const {data:s}=await browserDB()!.auth.getSession();const r=await fetch('/api/documents/'+d.id,{headers:{Authorization:'Bearer '+s.session?.access_token}});if(!r.ok)throw new Error((await r.json()).error);const url=URL.createObjectURL(await r.blob()),a=document.createElement('a');a.href=url;a.download=d.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 function exportCase(){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='lexmarket-'+id+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 if(!data) return <><button className="back-button" onClick={props.onBack}><ArrowLeft size={17}/>Volver</button><div className="notice-panel" role={loadError?'alert':'status'}>{loadError||'Abriendo tu espacio…'}</div></>;
 const activeRequests=data.requests.filter((r:Row)=>r.state==='granted');
 const activeLawyer=owner?(lawyerId||activeRequests[0]?.lawyer_id):session.user.id;
 const ownRequest=data.requests.find((r:Row)=>r.lawyer_id===session.user.id);
 const selectedLawyer=c.selected_lawyer===session.user.id;
 return <>
 <button className="back-button" onClick={props.onBack}><ArrowLeft size={17}/>Volver a {props.me.profile.role==='lawyer'?'los casos':'mi espacio'}</button>
 <div className="page-heading case-heading"><div><div className="inline-tags"><span className="tag soft">{c.category}</span><span className="tag">{statusLabels[c.status]}</span></div><h1>{c.title}</h1><p>{c.city} · Colombia <span className="dot-separator">·</span> {c.service}</p></div>{owner&&c.status==='draft'&&<button className="button" onClick={()=>setModal('publish')}>Compartir caso <ArrowRight size={17}/></button>}</div>
 {c.urgency==='urgent'&&<div className="notice-panel">Se ha indicado una situación urgente. Los tiempos que acuerdes aquí no sustituyen los plazos de una autoridad.</div>}
 {!hasPrivate?<section className="panel public-case"><div className="icon-square"><FileText size={24}/></div><h2>Una primera mirada</h2><p className="preserve">{c.public_summary}</p><div className="private-callout"><LockKeyhole size={22}/><div><h3>El expediente se comparte con autorización</h3><p>Cuéntale al cliente cómo podrías ayudarle. Si autoriza tu acceso, podrás revisar los documentos y enviar una propuesta.</p></div></div>{ownRequest?<span className="tag">{statusLabels[ownRequest.state]}</span>:<button className="button" onClick={()=>setModal('access')}>Me interesa este caso <ArrowRight size={17}/></button>}</section>:<>
 <nav className="tabs" aria-label="Secciones del caso">{[['overview','Mi caso'],['documents','Documentos'],['proposals',owner?'Abogados y propuestas':'Mi propuesta'],['messages','Conversaciones'],['progress','Seguimiento']].map(([k,v])=><button key={k} onClick={()=>setTab(k)} aria-current={tab===k?'page':undefined} className={tab===k?'active':''}>{v}{k==='documents'&&<span>{data.documents.length}</span>}{k==='proposals'&&<span>{data.proposals.length}</span>}</button>)}</nav>
 {tab==='overview'&&<div className="detail-grid"><div><section className="panel"><div className="split"><h2>El punto de partida</h2>{owner&&c.status==='draft'&&<button className="text-button" onClick={()=>setModal('edit')}>Editar</button>}</div><p className="preserve">{c.description}</p></section><section className="panel"><div className="split"><h2>Resumen para los abogados</h2><LockKeyhole size={18}/></div><p className="preserve">{c.public_summary||'Todavía no has preparado el resumen. Puedes escribirlo al editar tu caso o pedir una sugerencia a la organización asistida.'}</p><p className="microcopy">El título, la ciudad y este resumen son la primera información que comparten los profesionales verificados.</p>{owner&&c.status==='published'&&<button className="button outline small" onClick={()=>run(async()=>{await action('pause');onNotice('Publicación pausada. Ahora puedes editar el resumen.');})} disabled={busy}>Pausar para editar</button>}</section>
 {owner&&c.ai_result&&<section className="panel ai-result"><div className="split"><h2>Una propuesta de organización</h2><Sparkles size={20}/></div><p className="microcopy">Sugerencia de IA pendiente de tu revisión. No es un concepto jurídico.</p><span className="tag">{c.ai_result.category}</span><h3>{c.ai_result.title}</h3><p>{c.ai_result.summary}</p><h4>Elementos por aclarar</h4><ul>{c.ai_result.questions?.map((q:string)=><li key={q}>{q}</li>)}</ul><h4>Hechos mencionados</h4><ul>{c.ai_result.facts?.map((q:string)=><li key={q}>{q}</li>)}</ul>{c.ai_result.source_note&&<p className="notice-panel">{c.ai_result.source_note}</p>}{c.status==='draft'&&<button className="button outline" onClick={()=>{setSelected({...c,title:c.ai_result.title,category:c.ai_result.category,public_summary:c.ai_result.summary});setModal('edit-ai');}}>Revisar y ajustar la sugerencia <ArrowRight size={16}/></button>}</section>}</div>
 <aside><section className="panel next-step"><span className="overline">PARA SEGUIR AVANZANDO</span><h3>{c.status==='draft'?'A tu ritmo, en tu espacio':c.status==='published'?'Conoce tus opciones':'Mantengamos el hilo'}</h3><ul className="check-list"><li><Check size={16}/> Tu asunto está guardado.</li><li><Check size={16}/> {data.documents.length?'Tienes '+data.documents.length+' documento(s).':'Puedes agregar documentos cuando quieras.'}</li><li><Check size={16}/> {c.status==='draft'?'Tú decides cuándo compartirlo.':'Puedes revisar las novedades aquí.'}</li></ul><button className="button outline small" onClick={()=>setTab(c.status==='draft'?'documents':'proposals')}>{c.status==='draft'?'Agregar documentos':'Ver propuestas'}<ArrowRight size={16}/></button></section>
 {owner&&c.status==='draft'&&<section className="panel"><Sparkles size={22}/><h3>Un poco de ayuda para ordenar</h3><p>Podemos sugerir una categoría, reunir los hechos y preparar un resumen para que lo revises.</p><button className="text-button" disabled={busy||!props.me.ai||data.jobs.some((j:Row)=>j.kind==='organize'&&['queued','working'].includes(j.state))} onClick={()=>setModal('ai')}>{props.me.ai?'Organizar mi información':'Disponible al habilitar la IA'}<ArrowRight size={16}/></button>{data.jobs.filter((j:Row)=>j.kind==='organize').slice(0,1).map((j:Row)=><p className="microcopy" key={j.id}>{statusLabels[j.state]}{j.error?': '+j.error:''}</p>)}</section>}
 {owner&&<div className="stack-actions"><button className="text-button" onClick={exportCase}><Download size={16}/>Exportar información</button>{c.status==='draft'&&<button className="text-button danger" onClick={()=>setModal('delete-case')}><Trash2 size={16}/>Eliminar borrador</button>}</div>}</aside></div>}
 {tab==='documents'&&<section className="panel"><div className="section-heading"><div><h2>Todo lo que ayuda a entender tu caso</h2><p>El escrito principal, pruebas, respuestas recibidas o notas que quieras compartir.</p></div><LockKeyhole size={22}/></div>{c.status!=='closed'&&(owner||selectedLawyer)&&<UploadBox onFiles={files} busy={busy}/>}<p className="microcopy">Los archivos son opcionales. Para traer una conversación de ChatGPT u otra IA, guárdala como PDF/TXT o pega los fragmentos relevantes al editar el caso. Esta beta no accede a tus cuentas ni importa enlaces de chats.</p>{uploadProgress&&<p role="status">{uploadProgress}</p>}<div className="document-list">{data.documents.map((d:Row)=><div className="document-row" key={d.id}><span className="file-icon"><FileText size={20}/></span><div><b>{d.name}</b><small>{(d.size/1024).toFixed(0)} KB · {statusLabels[d.state]}</small>{d.extraction_note&&<small>{d.extraction_note}</small>}</div><button className="icon-button" aria-label={'Descargar '+d.name} disabled={d.state!=='clean'||busy} onClick={()=>run(()=>download(d))}><Download size={18}/></button>{owner&&<button className="icon-button danger" aria-label={'Eliminar '+d.name} disabled={busy} onClick={()=>{setSelected(d);setModal('delete-file');}}><Trash2 size={17}/></button>}</div>)}</div>{!data.documents.length&&<p className="muted">Todavía no hay archivos. No necesitas subirlos todos de una vez.</p>}</section>}
 {tab==='proposals'&&<>
 {owner&&<section className="panel"><h2>Profesionales interesados</h2><p className="muted">Conoce su perfil y decide a quién invitas a revisar el expediente. Autorizar acceso no equivale a contratar.</p>{data.requests.length?data.requests.map((r:Row)=><article className="request-row" key={r.id}><div className="request-profile"><span className="avatar">{name(r.lawyer_id).slice(0,1)}</span><div><button className="profile-name" onClick={()=>run(()=>showProfessional(r.lawyer_id))}>{name(r.lawyer_id)}<Chevron/></button><small>{statusLabels[r.state]}</small></div></div><p>{r.note}</p><div className="inline-actions">{r.state!=='granted'?<button className="button small outline" disabled={busy} onClick={()=>{setSelected(r);setModal('grant');}}>Autorizar acceso</button>:<><button className="button small" onClick={()=>{setLawyerId(r.lawyer_id);setTab('messages');}}>Conversar <MessageCircle size={15}/></button><button className="text-button" disabled={busy} onClick={()=>{setSelected(r);setModal('revoke');}}>Retirar acceso</button></>}</div></article>):<p className="notice-panel">Las solicitudes aparecerán aquí cuando un abogado se interese por tu caso.</p>}</section>}
 <div className="split section-title"><h2>{owner?'Propuestas para avanzar':'Tu propuesta'}</h2>{!owner&&c.status==='published'&&!data.proposals.length&&<button className="button" onClick={()=>setModal('proposal')}>Preparar propuesta <Plus size={17}/></button>}</div>
 {data.proposals.length?<div className="proposal-grid">{data.proposals.map((p:Row)=><article className="panel proposal-card" key={p.id}><div className="split"><button className="profile-name" onClick={()=>run(()=>showProfessional(p.lawyer_id))}>{name(p.lawyer_id)}</button><span className="tag">{statusLabels[p.status]}</span></div><div className="proposal-price">{money(p.amount)}<small>Honorarios propuestos · COP</small></div><h4>Qué incluye</h4><p className="preserve">{p.scope}</p><h4>Qué queda fuera</h4><p className="preserve">{p.exclusions}</p><h4>Tiempo estimado de trabajo</h4><p>{p.days} días desde el inicio acordado. No es un plazo de resolución judicial.</p><h4>Forma de pago propuesta</h4><p>{p.payment_terms}</p>{owner&&p.status==='pending'&&c.status==='published'&&<button className="button" disabled={busy} onClick={()=>{setSelected(p);setModal('accept');}}>Elegir esta propuesta <ArrowRight size={17}/></button>}</article>)}</div>:<Empty title={owner?'Demos lugar a una buena propuesta':'Explica cómo puedes ayudar'} text={owner?'Los profesionales autorizados podrán enviarte su alcance y honorarios después de revisar el expediente.':'Define entregables, límites, tiempos y honorarios. El cliente podrá comparar y decidir.'}/>}
 </>}
 {tab==='messages'&&<section className="panel"><div className="split"><h2>Una conversación a la vez</h2><button className="text-button" onClick={()=>run(refresh)}>Actualizar</button></div><p className="microcopy">Cada conversación es privada entre el cliente y ese profesional. Se actualiza cada 15 segundos.</p>{owner&&activeRequests.length>0&&<Field label="Con quién quieres conversar"><select value={activeLawyer} onChange={e=>setLawyerId(e.target.value)}>{activeRequests.map((r:Row)=><option key={r.lawyer_id} value={r.lawyer_id}>{name(r.lawyer_id)}</option>)}</select></Field>}{(owner?activeRequests.some((r:Row)=>r.lawyer_id===activeLawyer):ownRequest?.state==='granted')?<><div className="message-list">{data.messages.filter((m:Row)=>m.lawyer_id===activeLawyer).map((m:Row)=><article className={'message '+(m.sender_id===session.user.id?'mine':'')} key={m.id}><b>{m.sender_id===session.user.id?'Tú':m.sender_id===c.owner_id?'Cliente':name(m.sender_id)}</b><p>{m.body}</p><time>{date(m.created_at)}</time></article>)}{!data.messages.some((m:Row)=>m.lawyer_id===activeLawyer)&&<p className="muted">Este es un buen lugar para resolver las primeras dudas.</p>}</div><form className="message-composer" onSubmit={e=>{e.preventDefault();const form=e.currentTarget,body=new FormData(form).get('body');void run(async()=>{await action('messages',{lawyer_id:activeLawyer,body});form.reset();});}}><textarea name="body" required minLength={1} maxLength={4000} rows={3} aria-label="Mensaje" placeholder="Escribe tu mensaje…"/><button className="button" disabled={busy} aria-label="Enviar mensaje"><Send size={18}/></button></form></>:<Empty title="Primero, abre la conversación" text="La mensajería se habilita cuando el cliente autoriza el acceso al expediente."/>}</section>}
 {tab==='progress'&&<div className="detail-grid"><section className="panel"><h2>El camino hasta aquí</h2><p className="microcopy">Son actualizaciones registradas por los participantes. Una presentación debe acompañarse de su comprobante en Documentos.</p><ol className="timeline">{data.events.map((e:Row)=><li key={e.id}><span className="timeline-dot"/><time>{date(e.created_at)}</time><h3>{e.title}</h3>{e.detail&&<p className="preserve">{e.detail}</p>}</li>)}</ol>{selectedLawyer&&c.status==='engaged'&&<button className="button outline" onClick={()=>setModal('event')}><Plus size={17}/>Registrar actualización</button>}</section><aside><section className="panel"><h3>Un cierre claro también importa</h3><p>Cuando termine el acompañamiento, el cliente puede cerrar el espacio y compartir su experiencia.</p>{owner&&c.status==='engaged'&&<button className="button outline" onClick={()=>setModal('close')}>Cerrar acompañamiento</button>}{owner&&c.status==='closed'&&!data.reviews.length&&<button className="button" onClick={()=>setModal('review')}><Star size={17}/>Valorar mi experiencia</button>}{data.reviews?.map((r:Row,i:number)=><div className="review" key={i}><b>{'★'.repeat(r.rating)}{'☆'.repeat(5-r.rating)}</b><p>{r.comment}</p></div>)}</section></aside></div>}
 </>}
 {modal&&<Modal title={{edit:'Ajustemos los detalles','edit-ai':'Revisa la sugerencia antes de guardar',publish:'Una última mirada antes de compartir',access:'Cuéntale cómo puedes ayudar',grant:'Compartir el expediente',revoke:'Retirar acceso',proposal:'Una propuesta clara desde el principio',accept:'¿Avanzamos con esta propuesta?',ai:'Organicemos tu información',event:'Una novedad para tu cliente',close:'Cerrar este acompañamiento',review:'¿Cómo fue tu experiencia?',professional:'Conoce al profesional','delete-file':'Eliminar documento','delete-case':'Eliminar este borrador'}[modal]||''} onClose={()=>setModal('')}>
 {(modal==='edit'||modal==='edit-ai')&&<CaseForm initial={modal==='edit-ai'?selected||c:c} busy={busy} onSave={p=>run(async()=>{await api('cases/'+id,'PATCH',p);await refresh();setModal('');setSelected(null);onNotice('Cambios guardados.');})}/>}
 {modal==='publish'&&<form className="form-stack" onSubmit={e=>{e.preventDefault();const summary=String(new FormData(e.currentTarget).get('public_summary')||'');void run(async()=>{await api('cases/'+id,'PATCH',{...c,public_summary:summary});await action('publish',{reviewed:true});onNotice('Tu caso ya puede recibir solicitudes de abogados.');});}}><p>Esto es lo que verán los profesionales verificados:</p><div className="notice-panel"><b>{c.title}</b><p>{c.city} · {c.category}</p><Field label="Resumen para los abogados" hint="Cuenta brevemente qué buscas, sin nombres ni datos que identifiquen a las personas."><textarea name="public_summary" required minLength={30} maxLength={2000} rows={5} defaultValue={c.public_summary} placeholder="Lo que ocurrió y el acompañamiento que necesitas…"/></Field></div><label className="checkbox-line"><input type="checkbox" required/>Revisé el título, la ciudad y el resumen. No contienen datos que no quiera compartir ni identifican a personas involucradas.</label><p className="microcopy">Los documentos seguirán privados hasta que autorices cada acceso.</p><button className="button" disabled={busy}>Compartir caso <ArrowRight size={17}/></button></form>}
 {modal==='access'&&<form className="form-stack" onSubmit={e=>{e.preventDefault();void run(()=>action('access',{note:new FormData(e.currentTarget).get('note'),conflict_checked:true}));}}><Field label="Tu primera aproximación"><textarea name="note" minLength={20} maxLength={1000} required rows={5} placeholder="Qué experiencia tienes en este tipo de asunto y qué necesitarías revisar."/></Field><label className="checkbox-line"><input type="checkbox" required/>No identifico un conflicto con la información disponible. Verificaré las identidades y posibles conflictos antes de asesorar o asumir el caso.</label><button className="button" disabled={busy}>Solicitar acceso <ArrowRight size={17}/></button></form>}
 {modal==='grant'&&<><p>Autorizarás a <b>{name(selected!.lawyer_id)}</b> a leer el relato privado y descargar los documentos de este caso, incluidos los que agregues después.</p><p>Podrás retirar el acceso desde aquí. Los archivos que ya haya descargado no pueden recuperarse.</p><button className="button" disabled={busy} onClick={()=>run(()=>action('access',{lawyer_id:selected!.lawyer_id,state:'granted'},'PATCH'))}>Autorizar acceso</button></>}
 {modal==='revoke'&&<><p>El profesional dejará de acceder al expediente y a nuevas conversaciones. Esto no revoca un poder ni termina por sí solo un encargo acordado.</p><button className="button" disabled={busy} onClick={()=>run(()=>action('access',{lawyer_id:selected!.lawyer_id,state:'revoked'},'PATCH'))}>Retirar acceso</button></>}
 {modal==='proposal'&&<form className="form-stack" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void run(()=>action('proposals',{...Object.fromEntries(f),amount:Number(f.get('amount')),days:Number(f.get('days'))}));}}><Field label="Alcance y entregables"><textarea name="scope" minLength={30} maxLength={4000} required rows={4}/></Field><Field label="Qué no incluye"><textarea name="exclusions" required minLength={5} maxLength={2000} rows={3}/></Field><div className="form-grid"><Field label="Honorarios en COP"><input name="amount" type="number" min={0} max={1000000000} step={1} required/></Field><Field label="Días de trabajo estimados"><input name="days" type="number" min={1} max={365} step={1} required/></Field></div><Field label="Forma de pago y condiciones"><textarea name="payment_terms" minLength={5} maxLength={1000} required placeholder="Incluye impuestos aplicables, anticipos y gastos adicionales si los hay."/></Field><p className="microcopy">La propuesta quedará registrada sin edición. Confirma los detalles en la conversación antes de enviarla. No prometas resultados judiciales.</p><button className="button" disabled={busy}>Enviar propuesta <ArrowRight size={17}/></button></form>}
 {modal==='accept'&&<form className="form-stack" onSubmit={e=>{e.preventDefault();void run(()=>action('accept',{proposal_id:selected!.id,understood:true}));}}><div className="notice-panel"><b>{name(selected!.lawyer_id)}</b><p>{money(selected!.amount)}</p><p>{selected!.scope}</p></div><p>Las demás propuestas quedarán cerradas y se retirará el acceso de los otros profesionales. El precio y el alcance quedan registrados.</p><label className="checkbox-line"><input type="checkbox" required/>Entiendo que debo confirmar el encargo con el abogado y otorgar el poder que corresponda. Elegir una propuesta no presenta documentos ni realiza un pago.</label><button className="button" disabled={busy}>Elegir y continuar <ArrowRight size={17}/></button></form>}
 {modal==='ai'&&<form className="form-stack" onSubmit={e=>{e.preventDefault();void run(async()=>{await action('organize',{consent:true});onNotice('Estamos preparando una sugerencia. Puedes seguir usando tu espacio.');});}}><p>Se enviará a OpenAI el relato privado y el texto extraído de los documentos disponibles. La IA propondrá una categoría, hechos, preguntas y un resumen. Nada se publicará automáticamente.</p><p>Solo se incluyen archivos que ya terminaron de prepararse. Si alguno sigue pendiente, podrás volver a intentarlo después.</p><label className="checkbox-line"><input type="checkbox" required/>Autorizo este procesamiento de la información y revisaré la sugerencia antes de usarla.</label><button className="button" disabled={busy}><Sparkles size={17}/>Preparar sugerencia</button></form>}
 {modal==='event'&&<form className="form-stack" onSubmit={e=>{e.preventDefault();void run(()=>action('events',Object.fromEntries(new FormData(e.currentTarget))));}}><Field label="Qué ha avanzado"><select name="title">{['Encargo confirmado','Revisión en curso','Documentos ajustados','Actuación presentada','Novedad del proceso'].map(e=><option key={e}>{e}</option>)}</select></Field><Field label="Detalle para el cliente"><textarea name="detail" required minLength={10} maxLength={2000} rows={4} placeholder="Describe la novedad. Si hubo radicación, incluye autoridad, fecha y número, y adjunta el comprobante en Documentos."/></Field><button className="button" disabled={busy}>Registrar actualización</button></form>}
 {modal==='close'&&<><p>El espacio pasará a cerrado. Podrás consultar lo registrado y valorar la experiencia. Confirma previamente con el abogado el estado del encargo y cualquier obligación pendiente.</p><button className="button" disabled={busy} onClick={()=>run(()=>action('close'))}>Cerrar acompañamiento</button></>}
 {modal==='review'&&<form className="form-stack" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void run(()=>action('reviews',{rating:Number(f.get('rating')),comment:f.get('comment')}));}}><Field label="Tu valoración"><select name="rating">{[5,4,3,2,1].map(n=><option key={n} value={n}>{n} de 5</option>)}</select></Field><Field label="Qué destacarías" hint="El comentario será visible en el perfil. No incluyas datos del expediente ni nombres de terceros."><textarea name="comment" required minLength={10} maxLength={1000}/></Field><button className="button" disabled={busy}>Publicar valoración</button></form>}
 {modal==='professional'&&professional&&<><div className="professional-header"><span className="avatar large">{professional.profile.name.slice(0,1)}</span><div><h3>{professional.profile.name}</h3><p>{professional.profile.city}</p><span className="tag"><ShieldCheck size={14}/>{statusLabels[professional.profile.verification]}</span></div></div><p>{professional.profile.bio||'Este profesional todavía no ha agregado una presentación.'}</p><div className="inline-tags">{professional.profile.specialties.map((s:string)=><span className="tag soft" key={s}>{s}</span>)}</div><p className="microcopy">Verificación de habilitación{professional.profile.verified_at?' revisada el '+date(professional.profile.verified_at):' pendiente'}. No es una certificación de especialidad ni una garantía de resultados.</p><h3>Experiencias de clientes</h3>{professional.reviews.length?professional.reviews.map((r:Row,i:number)=><div className="review" key={i}><b>{r.rating} / 5</b><p>{r.comment}</p></div>):<p className="muted">Todavía no hay valoraciones. Solo pueden valorar clientes que hayan cerrado un acompañamiento en la plataforma.</p>}</>}
 {modal==='delete-file'&&<><p>Se eliminará <b>{selected!.name}</b> del expediente. Esta acción no elimina copias descargadas anteriormente.</p><button className="button danger-bg" disabled={busy} onClick={()=>run(async()=>{await api('documents/'+selected!.id,'DELETE');await refresh();setModal('');})}>Eliminar documento</button></>}
 {modal==='delete-case'&&<><p>Se eliminarán este borrador y sus archivos. Esta acción no se puede deshacer.</p><button className="button danger-bg" disabled={busy} onClick={()=>run(async()=>{await api('cases/'+id,'DELETE');setModal('');props.onBack();})}>Eliminar borrador</button></>}
 </Modal>}
 </>;
}
function Chevron(){return <ArrowRight size={14}/>;}
