'use client';
import { useEffect, useId, useRef, type ReactNode } from 'react';
import { X, ArrowRight, UploadCloud } from 'lucide-react';
import { categories, services } from '@/lib/shared';
export type Row=Record<string,any>;
export function Modal({title,children,onClose}:{title:string;children:ReactNode;onClose:()=>void}) {const ref=useRef<HTMLDialogElement>(null),id=useId();useEffect(()=>{ref.current?.showModal();},[]);return <dialog ref={ref} className="modal" aria-labelledby={id} onCancel={onClose}><div className="modal-head"><h2 id={id}>{title}</h2><button className="icon-button" aria-label="Cerrar" onClick={onClose}><X size={21}/></button></div>{children}</dialog>;}
export function Field({label,children,hint}:{label:string;children:ReactNode;hint?:string}) {return <label className="field"><span>{label}</span>{children}{hint&&<small>{hint}</small>}</label>;}
export function CaseForm({initial={},onSave,busy}:{initial?:Row;onSave:(data:Row)=>void;busy:boolean}) {return <form className="form-stack" onSubmit={e=>{e.preventDefault();onSave(Object.fromEntries(new FormData(e.currentTarget)));}}>
 <Field label="Dale un nombre a tu caso" hint="Evita nombres de personas, cédulas o datos que te identifiquen en el título."><input name="title" required minLength={8} maxLength={120} defaultValue={initial.title} placeholder="Por ejemplo, revisión de una reclamación laboral"/></Field>
 <div className="form-grid"><Field label="¿De qué se trata?"><select name="category" defaultValue={initial.category||'Otro'}>{categories.map(c=><option key={c}>{c}</option>)}</select></Field><Field label="Ciudad o municipio"><input name="city" required minLength={2} maxLength={80} defaultValue={initial.city} placeholder="Bogotá, Medellín…"/></Field></div>
 <Field label="¿Cómo te gustaría avanzar?"><select name="service" defaultValue={initial.service||services[0]}>{services.map(s=><option key={s}>{s}</option>)}</select></Field>
 <Field label="Cuéntanos sobre tu asunto" hint="Este texto es privado. Puedes pegar tus notas o los fragmentos relevantes de una conversación con IA."><textarea name="description" required minLength={30} maxLength={40000} rows={7} defaultValue={initial.description} placeholder="Qué ocurrió, qué has preparado y qué necesitas del abogado…"/></Field>
 <Field label="¿Hay algo urgente que debamos saber?"><select name="urgency" defaultValue={initial.urgency||'normal'}><option value="normal">Puedo revisar las opciones con calma</option><option value="soon">Me gustaría avanzar pronto</option><option value="urgent">Tengo una situación o un plazo urgente</option></select></Field>
 <p className="microcopy">Si hay una urgencia o un vencimiento, busca atención directa. Publicar aquí no suspende plazos ni garantiza una respuesta a tiempo.</p>
 {initial.id&&<Field label="Resumen para los abogados" hint="Se verá junto al título y la ciudad. Revisa que no incluya identidades ni información sensible."><textarea name="public_summary" maxLength={2000} rows={5} defaultValue={initial.public_summary}/></Field>}
 <button className="button" disabled={busy}>{busy?'Guardando…':initial.id?'Guardar cambios':'Crear mi espacio'}<ArrowRight size={17}/></button><p className="microcopy">Se guardará como borrador. Tú decides cuándo compartirlo.</p>
 </form>;}
export function ProfileForm({initial={},role='client',onSave,busy}:{initial?:Row;role?:string;onSave:(data:Row)=>void;busy:boolean}) {const isLawyer=(initial.role||role)==='lawyer';return <form className="form-stack" onSubmit={e=>{e.preventDefault();const data=new FormData(e.currentTarget);onSave({...Object.fromEntries(data),role:initial.role||role,specialties:data.getAll('specialties')});}}>
 <Field label="Tu nombre completo"><input name="name" required minLength={2} maxLength={100} defaultValue={initial.name}/></Field><Field label="Ciudad"><input name="city" maxLength={80} defaultValue={initial.city}/></Field>
 {isLawyer&&<><Field label="Número de tarjeta profesional (Colombia)" hint="El equipo comprobará tu habilitación antes de que puedas solicitar expedientes o enviar propuestas."><input name="license" required maxLength={80} defaultValue={initial.license}/></Field><Field label="Preséntate a tus futuros clientes"><textarea name="bio" rows={4} maxLength={1500} defaultValue={initial.bio} placeholder="Tu experiencia, tu forma de trabajar y en qué puedes ayudar."/></Field><fieldset className="specialties"><legend>Áreas de práctica</legend>{categories.map(c=><label key={c}><input type="checkbox" name="specialties" value={c} defaultChecked={initial.specialties?.includes(c)}/>{c}</label>)}</fieldset><p className="microcopy">Cambiar el nombre o la tarjeta profesional requiere una nueva verificación. La insignia acredita la revisión de habilitación; no garantiza resultados.</p></>}
 <button className="button" disabled={busy}>{busy?'Guardando…':'Guardar perfil'}<ArrowRight size={17}/></button>
 </form>;}
export function UploadBox({onFiles,busy}:{onFiles:(files:File[])=>void;busy:boolean}) {return <label className={'upload-box '+(busy?'disabled':'')} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(!busy)onFiles(Array.from(e.dataTransfer.files));}}><UploadCloud size={29}/><b>{busy?'Subiendo tus archivos…':'Arrastra tus documentos aquí'}</b><span>o elige los archivos de tu equipo</span><small>PDF, DOCX o TXT · hasta 10 MB por archivo · máximo 30 por caso</small><input type="file" multiple accept=".pdf,.docx,.txt" disabled={busy} aria-label="Seleccionar documentos" onChange={e=>{onFiles(Array.from(e.target.files||[]));e.target.value='';}}/></label>;}
