'use client';
import { useState } from 'react';
import { ArrowRight, Check, FileText, FolderOpen, HeartHandshake, LockKeyhole, MessageCircle, Plus, Scale, ShieldCheck, Sparkles } from 'lucide-react';
export function Brand(){return <span className="brand">lex<span>market</span><span className="brand-dot">.</span></span>;}
export default function Landing({onStart,onLawyer,onLogin,onInfo}:{onStart:()=>void;onLawyer:()=>void;onLogin:()=>void;onInfo:(s:string)=>void}) {
 const [example,setExample]=useState('Una tutela');
 const examples:Record<string,string>={'Una tutela':'Revisar y presentar mi tutela','Un asunto laboral':'Revisar una reclamación laboral','Una reclamación':'Dar el siguiente paso con mi reclamación','Un contrato':'Revisar y ajustar un contrato'};
 return <div className="landing">
  <header className="public-header wrap"><a href="#" aria-label="LexMarket inicio"><Brand/></a><nav aria-label="Principal"><a href="#como-funciona">Cómo funciona</a><a href="#preguntas">Preguntas</a><button className="text-button" onClick={onLawyer}>Para abogados</button></nav><button className="button small outline" onClick={onLogin}>Entrar <ArrowRight size={15}/></button></header>
  <main>
   <section className="hero wrap">
    <div className="hero-copy"><div className="eyebrow"><span className="tiny-dot"/> Un buen comienzo para lo que sigue</div><h1>Dale a tu caso<br/>el <em>siguiente paso.</em></h1><p className="hero-description">Encuentra al abogado que lo revise contigo y te acompañe a llevarlo adelante.</p><div className="hero-actions"><button className="button" aria-label="Compartir mi caso" onClick={onStart}>Empezar con mi caso <ArrowRight size={18}/></button><a className="quiet-link" href="#como-funciona">Conoce cómo funciona <span>↗</span></a></div><div className="hero-note"><LockKeyhole size={15}/> Tú decides con quién compartir tus documentos.</div></div>
    <div className="hero-visual" aria-label="Ejemplo ilustrativo de un espacio de caso"><img className="hero-image" src="/lexmarket-case-notes.svg" alt="Ilustración de notas y documentos organizados"/><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="floating-label"><HeartHandshake size={17}/> Un paso a la vez</div><div className="dossier-card"><div className="dossier-top"><div className="icon-square"><FolderOpen size={24}/></div><span className="tag">Tu espacio</span></div><span className="overline">ASÍ PODRÍA VERSE TU CASO</span><h2>{examples[example]}</h2><p>Todo en un lugar, para avanzar con claridad.</p><div className="file-row"><span className="file-icon"><FileText size={19}/></span><div><b>Lo que has preparado</b><span>Escritos, notas y documentos</span></div><Check size={16}/></div><div className="file-row"><span className="file-icon peach"><MessageCircle size={19}/></span><div><b>El acompañamiento que buscas</b><span>Revisión, ajustes o representación</span></div></div><div className="dossier-bottom"><span><span className="tiny-dot"/> El siguiente paso lo eliges tú</span><ArrowRight size={17}/></div></div><div className="floating-small"><ShieldCheck size={19}/><span>Compartir con<br/><b>tranquilidad</b></span></div></div>
   </section>
   <section className="examples wrap" aria-label="Ejemplos de asuntos"><p>Hay muchas formas de empezar.</p><div>{Object.keys(examples).map(e=><button key={e} className={'example-pill '+(example===e?'active':'')} aria-pressed={example===e} onClick={()=>setExample(e)}>{e}<Plus size={14}/></button>)}</div><small>Y otros asuntos que necesiten una mirada profesional.</small></section>
   <section className="journey-banner wrap"><img src="/lexmarket-journey.webp" width="1200" height="800" loading="lazy" alt="Una carpeta y documentos junto a un camino lila que lleva a una puerta abierta"/><div><span className="eyebrow">A TU RITMO</span><h2>Hay un siguiente paso.<br/>Encuentra con quién darlo.</h2><p>Reúne tus documentos, cuenta lo que buscas y conoce a los profesionales interesados en acompañarte.</p><button className="text-button" onClick={onStart}>Abrir mi espacio <ArrowRight size={17}/></button></div></section><section id="como-funciona" className="how-section"><div className="wrap"><div className="section-heading"><div><span className="overline">MENOS VUELTAS. MÁS CLARIDAD.</span><h2>De aquí, hacia adelante.</h2></div><p>Sin tener que contar la misma historia<br/>una y otra vez.</p></div><div className="steps-grid">{[{n:'01',icon:FolderOpen,title:'Abre tu espacio',text:'Comparte lo que tienes y cuéntanos qué te gustaría resolver. Puedes ir sumando documentos después.'},{n:'02',icon:Scale,title:'Conoce tus opciones',text:'Los abogados interesados te presentan una propuesta. Revisa su perfil, el alcance y los honorarios.'},{n:'03',icon:HeartHandshake,title:'Elige con quién avanzar',text:'Conversa, resuelve tus dudas y acuerda el acompañamiento que necesitas.'}].map(s=><article key={s.n} className="step-card"><div className="step-top"><s.icon size={25}/><span>{s.n}</span></div><h3>{s.title}</h3><p>{s.text}</p></article>)}</div></div></section>
   <section className="privacy-section wrap"><div className="privacy-art"><img src="/lexmarket-desk.svg" alt="Ilustración de un espacio de trabajo"/><span className="privacy-lock"><LockKeyhole size={22}/></span><span className="tag">Tú tienes el control</span></div><div><span className="overline">UN ESPACIO PARA TU TRANQUILIDAD</span><h2>Tu historia merece<br/>cuidado.</h2><p>Primero compartes un resumen. Tus archivos permanecen privados hasta que autorices a un abogado a revisarlos.</p><ul className="check-list"><li><Check size={17}/> Apruebas el resumen antes de publicarlo.</li><li><Check size={17}/> Decides quién puede abrir tu expediente.</li><li><Check size={17}/> Conoces el alcance antes de elegir.</li></ul></div></section>
   <section className="lawyer-banner wrap"><div><span className="overline">PARA ABOGADOS</span><h2>Tu próximo caso puede estar aquí.</h2><p>Explora asuntos de tu especialidad y propón cómo puedes acompañarlos.</p></div><button className="button light" onClick={onLawyer}>Crear perfil profesional <ArrowRight size={17}/></button></section>
   <section id="preguntas" className="faq wrap"><div><span className="overline">ANTES DE EMPEZAR</span><h2>Quizás te preguntes…</h2></div><div>{[
    ['¿Qué puedo compartir?','Una tutela, reclamación, demanda, contrato o cualquier asunto que quieras revisar con un abogado. Puedes adjuntar documentos y agregar notas o conversaciones que te hayan ayudado a prepararlo.'],
    ['¿Necesito tener todo terminado?','Puedes empezar con lo que tengas. Lo importante es explicar qué buscas y compartir el material que ayude a entender tu asunto. El profesional revisará contigo lo que haga falta.'],
    ['¿Qué verán los abogados?','Los profesionales verificados pueden explorar el resumen que apruebes. Para abrir tus documentos y conversar sobre el expediente, primero deberán solicitarte acceso.'],
    ['¿Publicar significa contratar?','Publicar no te obliga a elegir una propuesta. Cuando encuentres al profesional adecuado, deberán confirmar el encargo y, cuando corresponda, el poder antes de cualquier actuación.'],
    ['¿LexMarket presenta mi caso automáticamente?','La presentación corresponde al profesional que asuma la actuación, o a quien esté habilitado para hacerlo. La plataforma facilita el encuentro y el seguimiento.'],
   ].map(([q,a])=><details key={q}><summary>{q}<Plus size={18}/></summary><p>{a}</p></details>)}</div></section>
   <section className="final-cta wrap"><Sparkles size={24}/><h2>Lo que sigue, empieza con un paso.</h2><button className="button" onClick={onStart}>Empezar con mi caso <ArrowRight size={17}/></button></section>
  </main><footer className="wrap"><Brand/><span>Hecho para avanzar con más tranquilidad.</span><div><button onClick={()=>onInfo('privacy')}>Privacidad</button><button onClick={()=>onInfo('terms')}>Condiciones de la beta</button><button onClick={()=>onInfo('help')}>Ayuda</button></div></footer>
 </div>;
}
