'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {ArrowLeft,Check,CheckCheck,Download,FileText,MessageCircle,Paperclip,Send,ShieldCheck,X,Maximize2,Minimize2} from 'lucide-react';
import {api,browserDB} from '@/lib/browser';
import {Field,Modal,type Row} from './Forms';
import Avatar from './Avatar';
export type ChatTarget={case_id:string;lawyer_id:string};
const money=(n:number)=>new Intl.NumberFormat('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:0}).format(n);
const date=(s:string)=>new Date(s).toLocaleString('es-CO',{dateStyle:'medium',timeStyle:'short'});
export default function Messenger({userId,open,target,onOpen,onClose,onSelect,onCase}:{userId:string;open:boolean;target:ChatTarget|null;onOpen:()=>void;onClose:()=>void;onSelect:(t:ChatTarget|null)=>void;onCase:(id:string)=>void}){
 const [items,setItems]=useState<Row[]>([]),[error,setError]=useState(''),[query,setQuery]=useState(''),[expanded,setExpanded]=useState(false);
 const load=useCallback(async()=>{try{const d=await api('chats');setItems(d.items);setError('');}catch(e){setError((e as Error).message);}},[]);
 useEffect(()=>{void load();let timer:ReturnType<typeof setTimeout>;const refresh=()=>{clearTimeout(timer);timer=setTimeout(()=>void load(),250);};const db=browserDB()!;const channel=db.channel('inbox-'+userId).on('postgres_changes',{event:'*',schema:'public',table:'messages'},refresh).on('postgres_changes',{event:'*',schema:'public',table:'proposals'},refresh).subscribe();const poll=setInterval(()=>{if(document.visibilityState==='visible')void load();},30000);return ()=>{clearTimeout(timer);clearInterval(poll);void db.removeChannel(channel);};},[userId,load]);
 useEffect(()=>{if(open)void load();},[open,load]);
 const unread=items.reduce((n,i)=>n+i.unread,0);
 return <><button className="chat-launcher" onClick={open?onClose:onOpen} aria-label={open?'Cerrar mensajes':`Abrir mensajes${unread?', '+unread+' sin leer':''}`}><MessageCircle size={22}/><span>Mensajes</span>{unread>0&&<b>{unread>99?'99+':unread}</b>}</button>{open&&<section className={'messenger '+(expanded?'expanded':'')} aria-label="Mensajes privados"><header className="messenger-heading"><div><MessageCircle size={19}/><b>Conversaciones</b>{unread>0&&<span className="unread-pill">{unread}</span>}</div><div><button className="icon-button expand-chat" aria-label={expanded?'Reducir chat':'Ampliar chat'} onClick={()=>setExpanded(!expanded)}>{expanded?<Minimize2 size={17}/>:<Maximize2 size={17}/>}</button><button className="icon-button" onClick={onClose} aria-label="Cerrar mensajes"><X size={20}/></button></div></header>
 {target?<Conversation key={target.case_id+target.lawyer_id} target={target} userId={userId} onBack={()=>{onSelect(null);void load();}} onRead={()=>void load()} onCase={()=>onCase(target.case_id)}/>:<div className="chat-inbox"><div className="chat-intro"><h2>Sigamos conversando.</h2><p>Preguntas, documentos y acuerdos, en un mismo lugar.</p><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Busca una persona o un caso" aria-label="Buscar conversaciones"/></div>{error?<p className="notice-panel error">{error}<button onClick={()=>void load()}>Reintentar</button></p>:items.filter(i=>(i.peer.name+' '+i.title).toLowerCase().includes(query.toLowerCase())).map(i=><button className="inbox-row" key={i.case_id+i.lawyer_id} onClick={()=>onSelect({case_id:i.case_id,lawyer_id:i.lawyer_id})}><Avatar name={i.peer.name} url={i.peer.avatar_url}/><span><strong>{i.peer.name}</strong><small>{i.title}</small><p>{i.last?.sender_id===userId?'Tú: ':''}{i.last?.body||'La conversación está abierta. Saluda para empezar.'}</p></span>{i.unread>0&&<b className="unread-pill">{i.unread}</b>}</button>)}{!items.length&&!error&&<div className="chat-empty"><ShieldCheck size={32}/><h3>El primer encuentro empieza con confianza.</h3><p>Cuando autorices a un abogado a revisar tu caso, encontrarán aquí su conversación privada. Pueden hablar y definir honorarios antes de contratar.</p></div>}</div>}
 </section>}</>;
}
function Conversation({target,userId,onBack,onRead,onCase}:{target:ChatTarget;userId:string;onBack:()=>void;onRead:()=>void;onCase:()=>void}){
 const base='chats/'+target.case_id+'/'+target.lawyer_id;
 const draftKey='lexmarket.chat-draft.'+userId+'.'+target.case_id+'.'+target.lawyer_id;
 const [data,setData]=useState<Row|null>(null),[error,setError]=useState(''),[text,setText]=useState(''),[sending,setSending]=useState(false),[connected,setConnected]=useState(false),[offer,setOffer]=useState(false),[accept,setAccept]=useState<Row|null>(null),[older,setOlder]=useState(false),[tick,setTick]=useState(0);
 const scroll=useRef<HTMLDivElement>(null),bottom=useRef(true),fileInput=useRef<HTMLInputElement>(null),lastTyping=useRef(0),pending=useRef<{id:string;body:string}|null>(null),latest=useRef<Row|null>(null),readBusy=useRef(false),active=useRef(true);
 async function markRead(d:Row){if(readBusy.current||document.visibilityState!=='visible'||!document.hasFocus()||!bottom.current)return;const ids=d.messages.filter((m:Row)=>m.sender_id!==userId&&!m.read_at).map((m:Row)=>m.id).slice(-60);if(!ids.length)return;readBusy.current=true;try{await api(base+'/activity','POST',{read_ids:ids});onRead();}catch{}finally{readBusy.current=false;}}
 useEffect(()=>{try{setText(sessionStorage.getItem(draftKey)||'');}catch{}},[draftKey]);
 const refresh=useCallback(async()=>{try{const next=await api(base);if(!active.current)return;setData(prev=>{const map=new Map((prev?.messages||[]).map((m:Row)=>[m.id,m]));next.messages.forEach((m:Row)=>map.set(m.id,m));const files=new Map((prev?.files||[]).map((f:Row)=>[f.id,f]));next.files.forEach((f:Row)=>files.set(f.id,f));const combined={...next,messages:Array.from(map.values()).sort((a:any,b:any)=>a.created_at.localeCompare(b.created_at)||a.id.localeCompare(b.id)),files:Array.from(files.values()),hasMore:prev?.hasMore??next.hasMore};latest.current=combined;return combined;});setError('');}catch(e){if(active.current){setError((e as Error).message);setData(null);latest.current=null;}}},[base]);
 useEffect(()=>{active.current=true;void refresh();const db=browserDB()!;const channel=db.channel('thread-'+target.case_id+'-'+target.lawyer_id).on('postgres_changes',{event:'*',schema:'public',table:'messages',filter:'case_id=eq.'+target.case_id},()=>void refresh()).on('postgres_changes',{event:'*',schema:'public',table:'chat_activity',filter:'case_id=eq.'+target.case_id},()=>void refresh()).on('postgres_changes',{event:'*',schema:'public',table:'proposals',filter:'case_id=eq.'+target.case_id},()=>void refresh()).subscribe(status=>{setConnected(status==='SUBSCRIBED');if(status==='SUBSCRIBED')void refresh();});
 const heartbeat=()=>{if(document.visibilityState==='visible'&&document.hasFocus())void api(base+'/activity','POST',{}).catch(()=>{});};heartbeat();const poll=setInterval(()=>{if(document.visibilityState==='visible'){void refresh();heartbeat();}},25000);const clock=setInterval(()=>setTick(t=>t+1),5000);const focus=()=>{heartbeat();void refresh();};window.addEventListener('focus',focus);document.addEventListener('visibilitychange',focus);return ()=>{active.current=false;clearInterval(poll);clearInterval(clock);window.removeEventListener('focus',focus);document.removeEventListener('visibilitychange',focus);void db.removeChannel(channel);};},[base,refresh,target.case_id,target.lawyer_id]);
 useEffect(()=>{if(data){if(bottom.current&&scroll.current)scroll.current.scrollTop=scroll.current.scrollHeight;void markRead(data);}},[data,tick]);
 async function send(){if(!text.trim()||sending)return;setSending(true);setError('');if(!pending.current||pending.current.body!==text.trim())pending.current={id:crypto.randomUUID(),body:text.trim()};try{await api(base+'/messages','POST',pending.current);pending.current=null;setText('');try{sessionStorage.removeItem(draftKey);}catch{}bottom.current=true;await refresh();}catch(e){setError((e as Error).message);}finally{setSending(false);}}
 async function upload(file:File){setSending(true);setError('');try{if(file.size>10*1024*1024)throw new Error('El máximo por archivo es 10 MB.');const f=new FormData();f.append('file',file);f.append('id',crypto.randomUUID());await api(base+'/files','POST',f);bottom.current=true;await refresh();}catch(e){setError((e as Error).message);}finally{setSending(false);if(fileInput.current)fileInput.current.value='';}}
 async function download(f:Row){try{const {data:s}=await browserDB()!.auth.getSession();const r=await fetch('/api/chat-files/'+f.id,{headers:{Authorization:'Bearer '+s.session?.access_token}});if(!r.ok)throw new Error((await r.json()).error);const u=URL.createObjectURL(await r.blob()),a=document.createElement('a');a.href=u;a.download=f.name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}catch(e){setError((e as Error).message);}}
 async function loadOlder(){if(!data?.messages.length)return;setOlder(true);const height=scroll.current?.scrollHeight||0;try{const d=await api(base+'?before='+encodeURIComponent(data.messages[0].created_at));setData(prev=>prev?{...prev,messages:[...d.messages,...prev.messages.filter((m:Row)=>!d.messages.some((n:Row)=>n.id===m.id))],files:[...d.files,...prev.files],hasMore:d.hasMore}:prev);requestAnimationFrame(()=>{if(scroll.current)scroll.current.scrollTop=scroll.current.scrollHeight-height;});}catch(e){setError((e as Error).message);}finally{setOlder(false);}}
 const peerActivity=data?.activity.find((a:Row)=>a.user_id!==userId),online=peerActivity&&Date.now()-new Date(peerActivity.last_seen_at).getTime()<65000,typing=peerActivity?.typing_until&&new Date(peerActivity.typing_until).getTime()>Date.now();
 return <div className="conversation"><header className="conversation-peer"><button className="icon-button" onClick={onBack} aria-label="Volver a conversaciones"><ArrowLeft size={18}/></button>{data&&<><Avatar name={data.peer.name} url={data.peer.avatar_url}/><div><b>{data.peer.name}</b><small>{typing?'Está escribiendo…':online?'En esta conversación':peerActivity?'Última actividad: '+date(peerActivity.last_seen_at):'Aún no se ha conectado al chat'}</small></div></>}</header>{data&&<button className="chat-case-link" onClick={onCase}><FileText size={14}/><span>{data.case.title}</span><span>Ver caso ↗</span></button>}
 {!connected&&<p className="chat-network" role="status">Conectando en tiempo real… Actualizamos también al reconectar.</p>}{error&&<div className="chat-error" role="alert">{error}<button onClick={()=>void refresh()}>Reintentar</button></div>}
 <div className="chat-timeline" ref={scroll} onScroll={()=>{const e=scroll.current!;bottom.current=e.scrollHeight-e.scrollTop-e.clientHeight<45;if(bottom.current&&latest.current)void markRead(latest.current);}}>{data?.hasMore&&<button className="text-button" disabled={older} onClick={()=>void loadOlder()}>{older?'Cargando…':'Ver mensajes anteriores'}</button>}{data&&<p className="chat-privacy"><ShieldCheck size={14}/> Solo tú y {data.peer.name.split(' ')[0]} pueden ver esta conversación y sus adjuntos.</p>}
 {data&&[...data.messages.map((m:Row)=>({...m,kind:'message'})),...data.proposals.map((p:Row)=>({...p,kind:'proposal'}))].sort((a,b)=>a.created_at.localeCompare(b.created_at)||a.id.localeCompare(b.id)).map((m:Row)=>m.kind==='proposal'?<article className="chat-offer" key={m.id}><span className="overline">PROPUESTA DE ACOMPAÑAMIENTO</span><h3>{money(m.amount)} <small>COP</small></h3><p className="preserve">{m.scope}</p><details><summary>Alcance y condiciones</summary><p><b>No incluye:</b> {m.exclusions}</p><p><b>Forma de pago:</b> {m.payment_terms}</p><p>{m.days} días de trabajo estimados desde el inicio acordado.</p></details><small>{date(m.created_at)} · {m.status==='accepted'?'Elegida':m.status==='declined'?'Cerrada / reemplazada':'Por revisar'}</small>{data.owner&&m.status==='pending'&&data.case.status==='published'&&<button className="button small" onClick={()=>setAccept(m)}>Revisar y elegir</button>}</article>:<article className={'chat-bubble '+(m.sender_id===userId?'outgoing':'incoming')} key={m.id}>{m.attachment_id?(()=>{const f=data.files.find((f:Row)=>f.id===m.attachment_id);return f?<button className="chat-file" onClick={()=>void download(f)}><FileText size={24}/><span><b>{f.name}</b><small>{(f.size/1024).toFixed(0)} KB · Descargar</small></span><Download size={17}/></button>:<span>Documento no disponible</span>;})():<p>{m.body}</p>}<footer><time title={date(m.created_at)}>{new Date(m.created_at).toLocaleTimeString('es-CO',{hour:'2-digit',minute:'2-digit'})}</time>{m.sender_id===userId&&<span className={m.read_at?'read':''} title={m.read_at?'Leído '+date(m.read_at):m.delivered_at?'Entregado '+date(m.delivered_at):'Guardado en el servidor'}>{m.read_at||m.delivered_at?<CheckCheck size={13}/>:<Check size={13}/>} {m.read_at?'Leído':m.delivered_at?'Entregado':'Enviado'}</span>}</footer></article>)}{data&&!data.messages.length&&!data.proposals.length&&<div className="chat-empty"><h3>Un saludo abre el camino.</h3><p>Hablen de lo que necesitan revisar, los tiempos y cómo les gustaría trabajar.</p></div>}</div>
 {data&&<div className="chat-compose-area">{!data.owner&&data.case.status==='published'&&<button className="text-button" onClick={()=>setOffer(true)}>+ Proponer honorarios y alcance</button>}<form className="chat-composer" onSubmit={e=>{e.preventDefault();void send();}}><input hidden ref={fileInput} type="file" accept=".pdf,.docx,.txt" onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f);}}/><button type="button" className="icon-button" disabled={sending} onClick={()=>fileInput.current?.click()} aria-label="Adjuntar documento PDF, DOCX o TXT"><Paperclip size={20}/></button><textarea value={text} rows={2} maxLength={4000} aria-label="Escribe un mensaje" placeholder="Escribe con confianza…" onChange={e=>{setText(e.target.value);try{sessionStorage.setItem(draftKey,e.target.value);}catch{}if(Date.now()-lastTyping.current>4000){lastTyping.current=Date.now();void api(base+'/activity','POST',{typing:true}).catch(()=>{});}}} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();void send();}}}/><button className="chat-send" disabled={sending||!text.trim()} aria-label="Enviar mensaje"><Send size={19}/></button></form><small>{sending?'Enviando…':'PDF, DOCX o TXT · Hasta 10 MB · Mayús + Enter para otra línea'}</small></div>}
 {offer&&<Modal title="Dejemos el acuerdo claro" onClose={()=>setOffer(false)}><form className="form-stack" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);setSending(true);try{await api('cases/'+target.case_id+'/proposals','POST',{...Object.fromEntries(f),amount:Number(f.get('amount')),days:Number(f.get('days'))});setOffer(false);bottom.current=true;await refresh();}catch(e){setError((e as Error).message);setOffer(false);}finally{setSending(false);}}}><Field label="Qué vas a hacer y entregar"><textarea name="scope" required minLength={30} maxLength={4000}/></Field><Field label="Qué no está incluido"><textarea name="exclusions" required minLength={5} maxLength={2000}/></Field><div className="form-grid"><Field label="Honorarios (COP)"><input name="amount" type="number" required min={0} max={1000000000}/></Field><Field label="Días de trabajo estimados"><input name="days" type="number" required min={1} max={365}/></Field></div><Field label="Forma de pago, impuestos y gastos"><textarea name="payment_terms" required minLength={5} maxLength={1000}/></Field><p className="microcopy">Una nueva propuesta reemplaza la anterior pendiente y conserva su historial. El pago se acuerda directamente entre ustedes.</p><button className="button" disabled={sending}>Enviar propuesta</button></form></Modal>}
 {accept&&<Modal title="¿Avanzamos con esta propuesta?" onClose={()=>setAccept(null)}><h3>{money(accept.amount)}</h3><p>{accept.scope}</p><p>Al elegirla se cierran las demás propuestas y se retira el acceso de otros profesionales. No se realiza un pago ni se presentan documentos.</p><form className="form-stack" onSubmit={async e=>{e.preventDefault();setSending(true);try{await api('cases/'+target.case_id+'/accept','POST',{proposal_id:accept.id,understood:true});setAccept(null);await refresh();}catch(e){setError((e as Error).message);setAccept(null);}finally{setSending(false);}}}><label className="checkbox-line"><input type="checkbox" required/>Revisé las condiciones. Confirmaré el encargo y el poder que corresponda con el abogado.</label><button className="button" disabled={sending}>Elegir y continuar</button></form></Modal>}
 </div>;
}
