'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {ArrowLeft,Check,CheckCheck,Download,FileText,MessageCircle,Paperclip,Send,ShieldCheck,X,Maximize2,Minimize2} from 'lucide-react';
import {api,browserDB} from '@/lib/browser';
import {Field,Modal,type Row} from './Forms';
import Avatar from './Avatar';
export type ChatTarget={case_id:string;lawyer_id:string};
const threadCache=new Map<string,{value:Row;at:number}>();
const money=(n:number)=>new Intl.NumberFormat('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:0}).format(n);
const date=(s:string)=>new Date(s).toLocaleString('es-CO',{dateStyle:'medium',timeStyle:'short'});
export default function Messenger({userId,open,target,onOpen,onClose,onSelect,onCase,mode='floating',onAll}:{userId:string;open:boolean;target:ChatTarget|null;onOpen:()=>void;onClose:()=>void;onSelect:(t:ChatTarget|null)=>void;onCase:(id:string)=>void;mode?:'floating'|'page';onAll?:()=>void}){
 const [items,setItems]=useState<Row[]>([]),[error,setError]=useState(''),[query,setQuery]=useState(''),[windows,setWindows]=useState<ChatTarget[]>([]),[minimized,setMinimized]=useState<string[]>([]),[slots,setSlots]=useState(1);
 const key=(t:ChatTarget|Row)=>t.case_id+t.lawyer_id;
 const load=useCallback(async()=>{try{const d=await api('chats');setItems(d.items);setError('');}catch(e){setError((e as Error).message);}},[]);
 useEffect(()=>{const resize=()=>setSlots(Math.max(1,Math.min(3,Math.floor((window.innerWidth-210)/390))));resize();window.addEventListener('resize',resize);return ()=>window.removeEventListener('resize',resize);},[]);
 useEffect(()=>{if(target){setWindows(w=>[target,...w.filter(x=>key(x)!==key(target))]);setMinimized(m=>m.filter(k=>k!==key(target)));if(mode==='floating')onClose();}},[target]);
 useEffect(()=>{void load();let timer:ReturnType<typeof setTimeout>;const refresh=()=>{clearTimeout(timer);timer=setTimeout(()=>void load(),100);};const db=browserDB()!;const channel=db.channel('inbox-'+userId).on('postgres_changes',{event:'*',schema:'public',table:'messages'},refresh).on('postgres_changes',{event:'*',schema:'public',table:'proposals'},refresh).on('postgres_changes',{event:'*',schema:'public',table:'notifications',filter:'recipient_id=eq.'+userId},refresh).subscribe();window.addEventListener('lexmarket-update',refresh);const poll=setInterval(()=>{if(document.visibilityState==='visible')void load();},20000);return ()=>{clearTimeout(timer);clearInterval(poll);window.removeEventListener('lexmarket-update',refresh);void db.removeChannel(channel);};},[userId,load]);
 const unread=items.reduce((n,i)=>n+i.unread,0);
 const select=(t:ChatTarget)=>{onSelect(t);if(mode==='floating')onClose();};
 const inbox=<div className="chat-inbox"><div className="chat-intro"><h2>Mensajes</h2><p>Conversaciones, documentos y acuerdos.</p><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Busca una persona o un caso" aria-label="Buscar conversaciones"/></div>{error&&<p className="notice-panel error">{error}<button onClick={()=>void load()}>Reintentar</button></p>}{items.filter(i=>(i.peer.name+' '+i.title).toLowerCase().includes(query.toLowerCase())).map(i=><button className={'inbox-row '+(target&&key(target)===key(i)?'selected':'')} key={key(i)} onClick={()=>select({case_id:i.case_id,lawyer_id:i.lawyer_id})}><Avatar name={i.peer.name} url={i.peer.avatar_url}/><span><strong>{i.peer.name}</strong><small>{i.title}</small><p>{i.last?.sender_id===userId?'Tú: ':''}{i.last?.body||'Nueva solicitud. Pueden empezar a conversar.'}</p></span>{i.unread>0&&<b className="unread-pill">{i?.unread}</b>}</button>)}{!items.length&&!error&&<div className="chat-empty"><MessageCircle/><h3>Aquí empieza la conversación.</h3><p>Cuando un profesional muestre interés, podrán conversar y decidir qué información compartir.</p></div>}</div>;
 if(mode==='page')return <section className={'messages-page '+(target?'has-thread':'')} aria-label="Centro de mensajes">{inbox}<div className="messages-detail">{target?<Conversation key={key(target)} target={target} userId={userId} onBack={()=>onSelect(null)} onRead={()=>void load()} onCase={()=>onCase(target.case_id)}/>:<div className="chat-empty"><MessageCircle size={42}/><h2>Una conversación a la vez.</h2><p>Selecciona a alguien a la izquierda para continuar.</p></div>}</div></section>;
 const visible=windows.filter(t=>!minimized.includes(key(t))).slice(0,slots);
 return <><button className="chat-launcher" onClick={open?onClose:onOpen} aria-label="Abrir bandeja de mensajes"><MessageCircle size={22}/><span>Mensajes</span>{unread>0&&<b>{unread}</b>}</button>{open&&<section className="messenger inbox-popover"><header className="messenger-heading"><b>Conversaciones</b><button className="icon-button" onClick={onClose} aria-label="Cerrar bandeja"><X/></button></header>{inbox}<button className="button outline small" onClick={onAll}>Ver todos los mensajes</button></section>}
 <div className="chat-dock">{windows.map(t=>{const k=key(t),i=items.find(i=>key(i)===k),collapsed=!visible.some(v=>key(v)===k);return <section key={k} className={'dock-window '+(collapsed?'is-minimized':'')}><header className="messenger-heading dock-heading" title={collapsed?'Abrir conversación':'Minimizar conversación'} onClick={e=>{if((e.target as HTMLElement).closest('button'))return;if(collapsed){setMinimized(m=>m.filter(x=>x!==k));onSelect(t);}else setMinimized(m=>[...m,k]);}}><button className="dock-title" aria-expanded={!collapsed} onClick={()=>{if(collapsed){setMinimized(m=>m.filter(x=>x!==k));onSelect(t);}else setMinimized(m=>[...m,k]);}}>{i?.peer.name||'Conversación'}{i?.unread>0&&<b className="unread-pill">{i?.unread}</b>}</button><button className="icon-button" aria-label="Minimizar conversación" onClick={()=>setMinimized(m=>[...m,k])}><Minimize2 size={16}/></button><button className="icon-button" aria-label="Cerrar conversación" onClick={()=>{setWindows(w=>w.filter(x=>key(x)!==k));if(target&&key(target)===k)onSelect(null);}}><X size={17}/></button></header><div className="dock-body" hidden={collapsed}>{!collapsed&&<Conversation target={t} userId={userId} onBack={()=>onOpen()} onRead={()=>void load()} onCase={()=>onCase(t.case_id)}/>}</div></section>;})}</div></>;
}
function Conversation({target,userId,onBack,onRead,onCase}:{target:ChatTarget;userId:string;onBack:()=>void;onRead:()=>void;onCase:()=>void}){
 const base='chats/'+target.case_id+'/'+target.lawyer_id;
 const draftKey='lexmarket.chat-draft.'+userId+'.'+target.case_id+'.'+target.lawyer_id;
 const [outbox,setOutbox]=useState<Row[]>(()=>{try{return JSON.parse(sessionStorage.getItem(draftKey+'.outbox')||'[]').map((m:Row)=>({...m,local_state:m.local_state==='sent'?'sent':'failed'}));}catch{return [];}}),[data,setData]=useState<Row|null>(()=>{const saved=threadCache.get(draftKey);return saved&&Date.now()-saved.at<300000?saved.value:null;}),[error,setError]=useState(''),[text,setText]=useState(''),[sending,setSending]=useState(false),[connected,setConnected]=useState(false),[accessConfirm,setAccessConfirm]=useState(false),[offer,setOffer]=useState(false),[accept,setAccept]=useState<Row|null>(null),[older,setOlder]=useState(false),[tick,setTick]=useState(0);
 const scroll=useRef<HTMLDivElement>(null),bottom=useRef(true),fileInput=useRef<HTMLInputElement>(null),lastTyping=useRef(0),pending=useRef<{id:string;body:string}|null>(null),latest=useRef<Row|null>(null),readBusy=useRef(false),active=useRef(true),refreshFlight=useRef<Promise<void>|null>(null);
 useEffect(()=>{try{sessionStorage.setItem(draftKey+'.outbox',JSON.stringify(outbox));}catch{}},[outbox,draftKey]);
 useEffect(()=>{if(data)setOutbox(list=>{const next=list.filter(m=>!data.messages.some((n:Row)=>n.id===m.id));return next.length===list.length?list:next;});},[data]);
 async function markRead(d:Row){if(readBusy.current||document.visibilityState!=='visible'||!document.hasFocus()||!bottom.current)return;const ids=d.messages.filter((m:Row)=>m.sender_id!==userId&&!m.read_at).map((m:Row)=>m.id).slice(-60);if(!ids.length)return;readBusy.current=true;try{await api(base+'/activity','POST',{read_ids:ids});onRead();}catch{}finally{readBusy.current=false;}}
 useEffect(()=>{try{setText(sessionStorage.getItem(draftKey)||'');}catch{}},[draftKey]);
 const refresh=useCallback(()=>{if(refreshFlight.current)return refreshFlight.current;const task=(async()=>{try{const next=await api(base);if(!active.current)return;setData(prev=>{const map=new Map((prev?.messages||[]).map((m:Row)=>[m.id,m]));next.messages.forEach((m:Row)=>map.set(m.id,m));const files=new Map((prev?.files||[]).map((f:Row)=>[f.id,f]));next.files.forEach((f:Row)=>files.set(f.id,f));const combined={...next,messages:Array.from(map.values()).sort((a:any,b:any)=>a.created_at.localeCompare(b.created_at)||a.id.localeCompare(b.id)),files:Array.from(files.values()),hasMore:prev?.hasMore??next.hasMore};latest.current=combined;threadCache.delete(draftKey);threadCache.set(draftKey,{value:combined,at:Date.now()});if(threadCache.size>20)threadCache.delete(threadCache.keys().next().value!);return combined;});setError('');}catch(e){if(active.current){setError((e as Error).message);setData(null);threadCache.delete(draftKey);latest.current=null;}}})();refreshFlight.current=task;void task.finally(()=>{refreshFlight.current=null;});return task;},[base,draftKey]);
 useEffect(()=>{active.current=true;void refresh();const db=browserDB()!;const channel=db.channel('thread-'+target.case_id+'-'+target.lawyer_id).on('postgres_changes',{event:'*',schema:'public',table:'messages',filter:'case_id=eq.'+target.case_id},()=>void refresh()).on('postgres_changes',{event:'*',schema:'public',table:'chat_activity',filter:'case_id=eq.'+target.case_id},()=>void refresh()).on('postgres_changes',{event:'*',schema:'public',table:'proposals',filter:'case_id=eq.'+target.case_id},()=>void refresh()).subscribe(status=>{setConnected(status==='SUBSCRIBED');if(status==='SUBSCRIBED')void refresh();});
 const heartbeat=()=>{if(document.visibilityState==='visible'&&document.hasFocus())void api(base+'/activity','POST',{}).catch(()=>{});};heartbeat();const poll=setInterval(()=>{if(document.visibilityState==='visible'){void refresh();heartbeat();}},25000);const clock=setInterval(()=>setTick(t=>t+1),5000);const focus=()=>{heartbeat();void refresh();};window.addEventListener('focus',focus);document.addEventListener('visibilitychange',focus);return ()=>{active.current=false;clearInterval(poll);clearInterval(clock);window.removeEventListener('focus',focus);document.removeEventListener('visibilitychange',focus);void db.removeChannel(channel);};},[base,refresh,target.case_id,target.lawyer_id]);
 useEffect(()=>{if(data){if(bottom.current&&scroll.current)scroll.current.scrollTop=scroll.current.scrollHeight;void markRead(data);}},[data,tick,outbox]);
 async function transmit(m:Row){setOutbox(list=>list.map(x=>x.id===m.id?{...x,local_state:'sending'}:x));try{await api(base+'/messages','POST',{id:m.id,body:m.body});setOutbox(list=>list.map(x=>x.id===m.id?{...x,local_state:'sent'}:x));window.dispatchEvent(new Event('lexmarket-update'));await refresh();}catch(e){setOutbox(list=>list.map(x=>x.id===m.id?{...x,local_state:'failed'}:x));setError((e as Error).message);}}
 function send(){if(!text.trim())return;const m={id:crypto.randomUUID(),body:text.trim(),sender_id:userId,created_at:new Date().toISOString(),local_state:'sending'};setOutbox(list=>[...list,m]);setText('');setError('');try{sessionStorage.removeItem(draftKey);}catch{}bottom.current=true;void transmit(m);}

 async function upload(file:File){setSending(true);setError('');try{if(file.size>10*1024*1024)throw new Error('El máximo por archivo es 10 MB.');const f=new FormData();f.append('file',file);f.append('id',crypto.randomUUID());await api(base+'/files','POST',f);bottom.current=true;await refresh();}catch(e){setError((e as Error).message);}finally{setSending(false);if(fileInput.current)fileInput.current.value='';}}
 async function download(f:Row){try{const {data:s}=await browserDB()!.auth.getSession();const r=await fetch('/api/chat-files/'+f.id,{headers:{Authorization:'Bearer '+s.session?.access_token}});if(!r.ok)throw new Error((await r.json()).error);const u=URL.createObjectURL(await r.blob()),a=document.createElement('a');a.href=u;a.download=f.name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}catch(e){setError((e as Error).message);}}
 async function loadOlder(){if(!data?.messages.length)return;setOlder(true);const height=scroll.current?.scrollHeight||0;try{const d=await api(base+'?before='+encodeURIComponent(data.messages[0].created_at));setData(prev=>prev?{...prev,messages:[...d.messages,...prev.messages.filter((m:Row)=>!d.messages.some((n:Row)=>n.id===m.id))],files:[...d.files,...prev.files],hasMore:d.hasMore}:prev);requestAnimationFrame(()=>{if(scroll.current)scroll.current.scrollTop=scroll.current.scrollHeight-height;});}catch(e){setError((e as Error).message);}finally{setOlder(false);}}
 const peerActivity=data?.activity.find((a:Row)=>a.user_id!==userId),online=peerActivity&&Date.now()-new Date(peerActivity.last_seen_at).getTime()<65000,typing=peerActivity?.typing_until&&new Date(peerActivity.typing_until).getTime()>Date.now();
 return <div className="conversation"><header className="conversation-peer"><button className="icon-button" onClick={onBack} aria-label="Volver a conversaciones"><ArrowLeft size={18}/></button>{data&&<><Avatar name={data.peer.name} url={data.peer.avatar_url}/><div><b>{data.peer.name}</b><small>{typing?'Está escribiendo…':online?'En esta conversación':peerActivity?'Última actividad: '+date(peerActivity.last_seen_at):'Aún no se ha conectado al chat'}</small></div></>}</header>{data&&<button className="chat-case-link" onClick={onCase}><FileText size={14}/><span>{data.case.title}</span><span>Ver caso ↗</span></button>}
 {!connected&&<p className="chat-network" role="status">Conectando en tiempo real… Actualizamos también al reconectar.</p>}{error&&<div className="chat-error" role="alert">{error}<button onClick={()=>void refresh()}>Reintentar</button></div>}
 <div className="chat-timeline" ref={scroll} onScroll={()=>{const e=scroll.current!;bottom.current=e.scrollHeight-e.scrollTop-e.clientHeight<45;if(bottom.current&&latest.current)void markRead(latest.current);}}>{!data&&!error&&<div className="chat-loading" role="status"><span>Cargando conversación…</span><i/><i/><i/></div>}{data?.hasMore&&<button className="text-button" disabled={older} onClick={()=>void loadOlder()}>{older?'Cargando…':'Ver mensajes anteriores'}</button>}{data?.access_state==='requested'&&<div className="chat-access-card"><b>Conversemos antes de compartir el expediente</b><p>{data.case.summary}</p>{data.owner?<><p>Este profesional solicita revisar tus documentos privados. Conversar no le da acceso.</p><button className="button small" onClick={()=>setAccessConfirm(true)}>Revisar acceso</button></>:<p>Puedes preguntar al cliente mientras autoriza el acceso al expediente.</p>}</div>}{data&&<p className="chat-privacy"><ShieldCheck size={14}/> Solo tú y {data.peer.name.split(' ')[0]} pueden ver esta conversación y sus adjuntos.</p>}
 {data&&[...outbox.filter(m=>!data.messages.some((n:Row)=>n.id===m.id)).map(m=>({...m,kind:'message'})),...data.messages.map((m:Row)=>({...m,kind:'message'})),...data.proposals.map((p:Row)=>({...p,kind:'proposal'}))].sort((a,b)=>a.created_at.localeCompare(b.created_at)||a.id.localeCompare(b.id)).map((m:Row)=>m.kind==='proposal'?<article className="chat-offer" key={m.id}><span className="overline">PROPUESTA DE ACOMPAÑAMIENTO</span><h3>{money(m.amount)} <small>COP</small></h3><p className="preserve">{m.scope}</p><details><summary>Alcance y condiciones</summary><p><b>No incluye:</b> {m.exclusions}</p><p><b>Forma de pago:</b> {m.payment_terms}</p><p>{m.days} días de trabajo estimados desde el inicio acordado.</p></details><small>{date(m.created_at)} · {m.status==='accepted'?'Elegida':m.status==='declined'?'Cerrada / reemplazada':'Por revisar'}</small>{data.owner&&m.status==='pending'&&data.case.status==='published'&&<button className="button small" onClick={()=>setAccept(m)}>Revisar y elegir</button>}</article>:<article className={'chat-bubble '+(m.sender_id===userId?'outgoing':'incoming')} key={m.id}>{m.attachment_id?(()=>{const f=data.files.find((f:Row)=>f.id===m.attachment_id);return f?<button className="chat-file" onClick={()=>void download(f)}><FileText size={24}/><span><b>{f.name}</b><small>{(f.size/1024).toFixed(0)} KB · Descargar</small></span><Download size={17}/></button>:<span>Documento no disponible</span>;})():<p>{m.body}</p>}<footer><time title={date(m.created_at)}>{new Date(m.created_at).toLocaleTimeString('es-CO',{hour:'2-digit',minute:'2-digit'})}</time>{m.sender_id===userId&&<span className={m.read_at?'read':''} title={m.read_at?'Leído '+date(m.read_at):m.delivered_at?'Entregado '+date(m.delivered_at):'Guardado en el servidor'}>{m.local_state==='sending'||m.local_state==='failed'?null:m.read_at||m.delivered_at?<CheckCheck size={13}/>:<Check size={13}/>} {m.local_state==='sending'?'Enviando…':m.local_state==='failed'?'No enviado':m.read_at?'Leído':m.delivered_at?'Entregado':'Enviado'}</span>}</footer>{m.local_state==='failed'&&<button className="retry-message" onClick={()=>void transmit(m)}>Reintentar envío</button>}</article>)}{data&&!outbox.length&&!data.messages.length&&!data.proposals.length&&<div className="chat-empty"><h3>Un saludo abre el camino.</h3><p>Hablen de lo que necesitan revisar, los tiempos y cómo les gustaría trabajar.</p></div>}</div>
 {data&&<div className="chat-compose-area">{!data.owner&&data.access_state==='granted'&&data.case.status==='published'&&<button className="text-button" onClick={()=>setOffer(true)}>+ Proponer honorarios y alcance</button>}<form className="chat-composer" onSubmit={e=>{e.preventDefault();void send();}}><input hidden ref={fileInput} type="file" accept=".pdf,.docx,.txt" onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f);}}/><button type="button" className="icon-button" disabled={sending} onClick={()=>fileInput.current?.click()} aria-label="Adjuntar documento PDF, DOCX o TXT"><Paperclip size={20}/></button><textarea value={text} rows={2} maxLength={4000} aria-label="Escribe un mensaje" placeholder="Escribe con confianza…" onChange={e=>{setText(e.target.value);try{sessionStorage.setItem(draftKey,e.target.value);}catch{}if(Date.now()-lastTyping.current>4000){lastTyping.current=Date.now();void api(base+'/activity','POST',{typing:true}).catch(()=>{});}}} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();void send();}}}/><button className="chat-send" disabled={!text.trim()} aria-label="Enviar mensaje"><Send size={19}/></button></form><small>{sending?'Enviando…':'PDF, DOCX o TXT · Hasta 10 MB · Mayús + Enter para otra línea'}</small></div>}
 {accessConfirm&&<Modal title="¿Compartir el expediente con este profesional?" onClose={()=>setAccessConfirm(false)}><p>Podrá leer los hechos privados y descargar los documentos del caso. Autorizar acceso no equivale a contratar.</p><button className="button" disabled={sending} onClick={async()=>{setSending(true);try{await api('cases/'+target.case_id+'/access','PATCH',{lawyer_id:target.lawyer_id,state:'granted'});setAccessConfirm(false);window.dispatchEvent(new Event('lexmarket-update'));await refresh();}catch(e){setError((e as Error).message);}finally{setSending(false);}}}>Autorizar acceso</button><button className="button outline" disabled={sending} onClick={async()=>{setSending(true);try{await api('cases/'+target.case_id+'/access','PATCH',{lawyer_id:target.lawyer_id,state:'revoked'});setAccessConfirm(false);window.dispatchEvent(new Event('lexmarket-update'));await refresh();}catch(e){setError((e as Error).message);}finally{setSending(false);}}}>Rechazar solicitud</button></Modal>}
 {offer&&<Modal title="Dejemos el acuerdo claro" onClose={()=>setOffer(false)}><form className="form-stack" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);setSending(true);try{await api('cases/'+target.case_id+'/proposals','POST',{...Object.fromEntries(f),amount:Number(f.get('amount')),days:Number(f.get('days'))});setOffer(false);bottom.current=true;await refresh();}catch(e){setError((e as Error).message);setOffer(false);}finally{setSending(false);}}}><Field label="Qué vas a hacer y entregar"><textarea name="scope" required minLength={30} maxLength={4000}/></Field><Field label="Qué no está incluido"><textarea name="exclusions" required minLength={5} maxLength={2000}/></Field><div className="form-grid"><Field label="Honorarios (COP)"><input name="amount" type="number" required min={0} max={1000000000}/></Field><Field label="Días de trabajo estimados"><input name="days" type="number" required min={1} max={365}/></Field></div><Field label="Forma de pago, impuestos y gastos"><textarea name="payment_terms" required minLength={5} maxLength={1000}/></Field><p className="microcopy">Una nueva propuesta reemplaza la anterior pendiente y conserva su historial. El pago se acuerda directamente entre ustedes.</p><button className="button" disabled={sending}>Enviar propuesta</button></form></Modal>}
 {accept&&<Modal title="¿Avanzamos con esta propuesta?" onClose={()=>setAccept(null)}><h3>{money(accept.amount)}</h3><p>{accept.scope}</p><p>Al elegirla se cierran las demás propuestas y se retira el acceso de otros profesionales. No se realiza un pago ni se presentan documentos.</p><form className="form-stack" onSubmit={async e=>{e.preventDefault();setSending(true);try{await api('cases/'+target.case_id+'/accept','POST',{proposal_id:accept.id,understood:true});setAccept(null);await refresh();}catch(e){setError((e as Error).message);setAccept(null);}finally{setSending(false);}}}><label className="checkbox-line"><input type="checkbox" required/>Revisé las condiciones. Confirmaré el encargo y el poder que corresponda con el abogado.</label><button className="button" disabled={sending}>Elegir y continuar</button></form></Modal>}
 </div>;
}
