'use client';
import { useEffect, useState } from 'react';
import type { Session } from '@supabase/supabase-js';
import { ArrowLeft, ArrowRight, BriefcaseBusiness, ChevronRight, CircleHelp, Compass, FolderOpen, LayoutDashboard, LogOut, Plus, Search, Settings, ShieldCheck } from 'lucide-react';
import { api } from '@/lib/browser';
import { categories, statusLabels } from '@/lib/shared';
import { Brand } from './Landing';
import { CaseForm, Field, Modal, ProfileForm, type Row } from './Forms';
import CaseIntake from './CaseIntake';
import {importIntake} from '@/lib/import-intake';
import CaseView from './CaseView';
import Avatar from './Avatar';
import Messenger, {type ChatTarget} from './Messenger';
import { MessageCircle, Home } from 'lucide-react';
export type Run=(fn:()=>Promise<void>)=>Promise<void>;
export type WorkProps={me:Row;session:Session;run:Run;busy:boolean;onNotice:(s:string)=>void;onInfo:(s:string)=>void;onRefreshMe:()=>Promise<void>;onLogout:()=>void;pendingImport?:React.ReactNode;onChat?:(caseId:string,lawyerId:string)=>void};
export default function Workspace(props:WorkProps) {
 const {me,run,busy,onNotice}=props,p=me.profile,isLawyer=p.role==='lawyer';
 const [view,setView]=useState('welcome'),[caseId,setCaseId]=useState(''),[items,setItems]=useState<Row[]>([]),[loading,setLoading]=useState(true),[loadError,setLoadError]=useState(''),[create,setCreate]=useState(false),[query,setQuery]=useState(''),[category,setCategory]=useState(''),[revision,setRevision]=useState(0),[admin,setAdmin]=useState<Row|null>(null);
 const [chatOpen,setChatOpen]=useState(false),[chatTarget,setChatTarget]=useState<ChatTarget|null>(null);
 const avatar=p.avatar_url||props.session.user.user_metadata?.avatar_url||props.session.user.user_metadata?.picture;
 function openChat(caseId:string,lawyerId:string){setChatTarget({case_id:caseId,lawyer_id:lawyerId});setChatOpen(true);}
 useEffect(()=>{let active=true;setLoadError('');if(view==='profile'){setLoading(false);return;}if(view==='marketplace'&&p.verification!=='verified'){setItems([]);setLoading(false);return;}setLoading(true);api(view==='admin'?'admin':view==='marketplace'?'marketplace':'cases').then(data=>{if(!active)return;if(view==='admin')setAdmin(data);else setItems(data.items);}).catch(e=>{if(active)setLoadError(e.message);}).finally(()=>{if(active)setLoading(false);});return ()=>{active=false;};},[view,revision,p.verification]);
 function navigate(v:string){if(v==='messages'){setChatOpen(true);setChatTarget(null);return;}setView(v);setCaseId('');setQuery('');setCategory('');}
 const filtered=items.filter(c=>(!category||c.category===category)&&[c.title,c.city,c.summary].join(' ').toLocaleLowerCase().includes(query.toLocaleLowerCase()));
 return <div className="app-shell"><aside className="sidebar"><a href="/" className="sidebar-brand" aria-label="Inicio"><Brand/></a><div className="workspace-label">{isLawyer?'ESPACIO PROFESIONAL':'TU ESPACIO'}</div><nav aria-label="Tu espacio">{[{id:'welcome',label:'Inicio',icon:Home},{id:'messages',label:'Mensajes',icon:MessageCircle},{id:'cases',label:isLawyer?'Mis oportunidades':'Mis casos',icon:FolderOpen},...(isLawyer?[{id:'marketplace',label:'Explora casos',icon:Compass}]:[]),{id:'profile',label:'Mi perfil',icon:Settings},...(me.admin?[{id:'admin',label:'Verificaciones',icon:ShieldCheck}]:[])].map(n=><button key={n.id} className={view===n.id?'selected':''} onClick={()=>navigate(n.id)}><n.icon size={19}/>{n.label}{view===n.id&&<span className="nav-dot"/>}</button>)}</nav><div className="sidebar-bottom"><button onClick={()=>props.onInfo('help')}><CircleHelp size={18}/>¿Te ayudamos?</button><div className="account"><Avatar name={p.name} url={avatar}/><div><b>{p.name}</b><small>{isLawyer?'Cuenta profesional':'Cuenta personal'}</small></div><button aria-label="Cerrar sesión" onClick={props.onLogout}><LogOut size={17}/></button></div></div></aside>
 <div className="workspace"><header className="workspace-top"><span><span className="tiny-dot"/> Un paso a la vez</span><div><span className="tag">Beta · Colombia</span><button className="icon-button" aria-label="Ayuda" onClick={()=>props.onInfo('help')}><CircleHelp size={19}/></button></div></header><main className="workspace-main">
 {props.pendingImport}
 {caseId?<CaseView {...props} onChat={openChat} id={caseId} onBack={()=>{setCaseId('');setRevision(n=>n+1);}}/>:<>
 {view==='welcome'?<><section className="welcome-card"><div className="welcome-copy"><Avatar name={p.name} url={avatar} large/><span className="overline">ESTÁS EN TU ESPACIO</span><h1>Qué bueno verte,<br/><em>{p.name.split(' ')[0]}.</em></h1><p>{isLawyer?'Hay conversaciones que pueden convertirse en un buen acompañamiento. Empecemos por ahí.':'Lo que sigue se siente más fácil cuando tienes con quién hablar. Aquí retomamos el camino.'}</p><button className="button" onClick={()=>isLawyer?navigate('marketplace'):items.length?navigate('cases'):setCreate(true)}>{isLawyer?'Explorar casos':items.length?'Retomar mis casos':'Compartir mi caso'}<ArrowRight size={18}/></button></div><img className="welcome-art" src="/lexmarket-journey.webp" alt="Carpetas en tonos lavanda, un espacio para organizar tu siguiente paso"/></section><div className="welcome-actions"><button onClick={()=>{setChatTarget(null);setChatOpen(true);}}><span className="icon-square"><MessageCircle size={23}/></span><h3>Una buena conversación</h3><p>Resuelve dudas, comparte documentos y acuerda cómo avanzar.</p><span className="text-button">Abrir mensajes <ArrowRight size={16}/></span></button><button onClick={()=>navigate('cases')}><span className="icon-square"><FolderOpen size={23}/></span><h3>Todo encuentra su lugar</h3><p>Tus casos, propuestas y próximos pasos, reunidos aquí.</p><span className="text-button">Ir a mi espacio <ArrowRight size={16}/></span></button><button onClick={()=>navigate('profile')}><span className="icon-square"><ShieldCheck size={23}/></span><h3>Detrás de cada caso, tú</h3><p>Cuida tu presentación y mantén tus datos al día.</p><span className="text-button">Ver mi perfil <ArrowRight size={16}/></span></button></div>{items.length>0&&<section className="welcome-recent"><span className="overline">DONDE LO DEJAMOS</span>{items.slice(0,3).map(c=><button key={c.id} onClick={()=>setCaseId(c.id)}><FolderOpen size={20}/><span><b>{c.title}</b><small>{c.city} · {statusLabels[c.status]}</small></span><ArrowRight size={18}/></button>)}</section>}</>:view==='profile'?<><div className="page-heading"><div><span className="overline">LAS PERSONAS DETRÁS DE CADA CASO</span><h1>Tu perfil</h1><p>Una buena presentación también abre puertas.</p></div>{isLawyer&&<span className="tag">{statusLabels[p.verification]}</span>}</div><section className="panel narrow"><div className="profile-photo"><Avatar name={p.name} url={avatar} large/><p>{avatar?'Tu foto de Google te acompaña en LexMarket.':'Tu inicial identifica tu perfil.'}</p></div><ProfileForm initial={p} busy={busy} onSave={data=>run(async()=>{await api('me','PUT',data);await props.onRefreshMe();onNotice('Tu perfil está actualizado.');})}/>{p.verification_note&&<p className="notice-panel">Nota de verificación: {p.verification_note}</p>}</section></>:
 view==='admin'?<><div className="page-heading"><div><span className="overline">ADMINISTRACIÓN</span><h1>Verificación profesional</h1><p>Comprueba identidad y habilitación en fuentes oficiales. Registra la fuente y la fecha.</p></div></div>{admin?.profiles.map((l:Row)=><article className="panel" key={l.id}><div className="split"><div><h3>{l.name}</h3><p>T.P. {l.license} · {l.city}</p></div><span className="tag">{statusLabels[l.verification]}</span></div><p>{l.bio}</p><form className="form-stack" onSubmit={e=>{e.preventDefault();const data=new FormData(e.currentTarget);void run(async()=>{await api('admin/'+l.id,'PATCH',{verification:data.get('verification'),note:data.get('note')});setRevision(n=>n+1);onNotice('Revisión registrada.');});}}><Field label="Resultado"><select name="verification"><option value="verified">Verificado</option><option value="rejected">Requiere ajustes / suspender acceso</option></select></Field><Field label="Evidencia de la comprobación"><textarea name="note" required minLength={20} maxLength={2000} placeholder="Fuente oficial consultada, fecha, identidad cotejada y resultado…"/></Field><button className="button small" disabled={busy}>Guardar revisión</button></form></article>)}{!loading&&!admin?.profiles.length&&<Empty title="Aún no hay perfiles por revisar" text="Aquí aparecerán las solicitudes de los profesionales."/>}</>:
 <><div className="page-heading"><div><span className="overline">{view==='marketplace'?'ENCUENTRA DÓNDE PUEDES APORTAR':isLawyer?'TUS CONVERSACIONES Y PROPUESTAS':'QUÉ BUENO VERTE POR AQUÍ'}</span><h1>{view==='marketplace'?'Explora casos':isLawyer?'Mis oportunidades':`Hola, ${p.name.split(' ')[0]}.`}</h1><p>{view==='marketplace'?'Una primera mirada para encontrar tu próximo encargo.':isLawyer?'Retoma los asuntos en los que has mostrado interés.':'Este es el lugar para lo que sigue.'}</p></div>{!isLawyer&&<button className="button" onClick={()=>setCreate(true)}><Plus size={18}/>Compartir un caso</button>}</div>
 {isLawyer&&p.verification!=='verified'?<div className="verification-card"><ShieldCheck size={35}/><h2>Vamos a conocerte mejor.</h2><p>Tu perfil está {p.verification==='rejected'?'pendiente de ajustes':'en revisión'}. En cuanto comprobemos tu habilitación, podrás explorar casos y enviar propuestas.</p>{p.verification_note&&<p>{p.verification_note}</p>}<button className="button outline" onClick={()=>navigate('profile')}>Revisar mi perfil <ArrowRight size={17}/></button></div>:<>
 {view==='cases'&&<div className="stat-grid"><div><span>En tu espacio</span><b>{items.length}</b></div><div><span>{isLawyer?'Con acceso':'Recibiendo propuestas'}</span><b>{items.filter(c=>isLawyer?c.access_state==='granted':c.status==='published').length}</b></div><div><span>En acompañamiento</span><b>{items.filter(c=>c.status==='engaged').length}</b></div></div>}
 <div className="list-toolbar"><div className="search"><Search size={18}/><input aria-label="Buscar casos" placeholder="Busca por asunto o ciudad" value={query} onChange={e=>setQuery(e.target.value)}/></div><select aria-label="Filtrar especialidad" value={category} onChange={e=>setCategory(e.target.value)}><option value="">Todas las áreas</option>{categories.map(c=><option key={c}>{c}</option>)}</select><button className="text-button" onClick={()=>setRevision(n=>n+1)}>Actualizar</button></div>
 {loading?<div className="skeleton-list" aria-label="Cargando casos"><div/><div/><div/></div>:filtered.length?<div className="case-grid">{filtered.map(c=><button key={c.id||c.case_id} className="case-card" onClick={()=>setCaseId(c.id||c.case_id)}><div className="split"><span className="tag soft">{c.category}</span>{c.urgency==='urgent'&&<span className="urgency">Solicita atención pronta</span>}</div><h3>{c.title}</h3>{c.summary&&<p>{c.summary}</p>}<span className="case-location">{c.city} · Colombia</span><div className="case-card-bottom"><span>{view==='marketplace'?c.service:statusLabels[c.access_state||c.status]}</span><ArrowRight size={18}/></div></button>)}</div>:<Empty title={query||category?'No encontramos coincidencias':view==='marketplace'?'Los próximos casos aparecerán aquí':isLawyer?'Aquí empiezan tus oportunidades':'Hagamos espacio para tu siguiente paso'} text={query||category?'Prueba con otra búsqueda o especialidad.':view==='marketplace'?'Vuelve pronto para conocer nuevos asuntos.':isLawyer?'Explora los casos y solicita acceso a los que te interesen.':'Comparte tu asunto y reúne lo que has preparado. Puedes completar los detalles a tu ritmo.'} action={!isLawyer?<button className="button" onClick={()=>setCreate(true)}>Crear mi primer espacio <ArrowRight size={17}/></button>:undefined}/>}</>}
 </>}
 {loadError&&<div className="notice-panel error" role="alert">{loadError}<button className="text-button" onClick={()=>setRevision(n=>n+1)}>Reintentar</button></div>}
 </>}
 </main></div>{create&&<CaseIntake signedIn onClose={()=>setCreate(false)} onReady={()=>run(async()=>{const id=await importIntake(props.session.user.id,onNotice);setCreate(false);setCaseId(id);onNotice('Tu caso está guardado. Revisa el resumen antes de compartirlo.');})}/>}
 <Messenger userId={props.session.user.id} open={chatOpen} target={chatTarget} onOpen={()=>setChatOpen(true)} onClose={()=>setChatOpen(false)} onSelect={setChatTarget} onCase={id=>{setChatOpen(false);setCaseId(id);}}/>
 </div>;
}
export function Empty({title,text,action}:{title:string;text:string;action?:React.ReactNode}) {return <div className="empty-state"><div className="empty-icon"><FolderOpen size={31}/></div><h2>{title}</h2><p>{text}</p>{action}</div>;}
