import type { LawyerData } from '@/components/LawyerCard';

export const SEED_FEATURED_LAWYERS: LawyerData[] = [
  {
    id: 'seed-lawyer-1',
    name: 'María Fernanda López',
    city: 'Bogotá',
    bio: 'Especialista en Derecho Laboral y Seguridad Social con 12 años de experiencia asesorando a trabajadores y empresas en la resolución de conflictos, negociaciones y litigios.',
    specialties: ['Derecho Laboral', 'Derecho Civil'],
    verification: 'verified',
    avatar_url: '/lawyers/maria-fernanda.png',
    years_of_experience: 12,
    rating: 4.9,
    review_count: 87,
    featured: true,
    featured_review: 'Muy clara durante todo el proceso y siempre respondió rápido.',
  },
  {
    id: 'seed-lawyer-2',
    name: 'Santiago Ramírez',
    city: 'Medellín',
    bio: 'Especialista en Derecho de Familia, divorcios, custodia y acuerdos sucesorales con un enfoque humano y conciliador.',
    specialties: ['Derecho de Familia', 'Derecho Civil'],
    verification: 'verified',
    avatar_url: '/lawyers/santiago.png',
    years_of_experience: 9,
    rating: 4.8,
    review_count: 54,
    featured: true,
    featured_review: 'Me dio mucha confianza y explicó todo de forma sencilla.',
  },
  {
    id: 'seed-lawyer-3',
    name: 'Valentina Torres',
    city: 'Cali',
    bio: 'Experta en Derecho Civil, contratos, reclamaciones de responsabilidad y restitución de inmuebles.',
    specialties: ['Derecho Civil', 'Derecho Inmobiliario'],
    verification: 'verified',
    avatar_url: '/lawyers/valentina.png',
    years_of_experience: 11,
    rating: 5.0,
    review_count: 31,
    featured: true,
    featured_review: 'Excelente acompañamiento y muy organizada con los documentos.',
  },
  {
    id: 'seed-lawyer-4',
    name: 'Andrés Mejía',
    city: 'Bogotá',
    bio: 'Asesoría jurídica en Derecho Comercial, contratos societarios y controversias mercantiles.',
    specialties: ['Derecho Comercial', 'Derecho Administrativo'],
    verification: 'verified',
    avatar_url: '/lawyers/andres.png',
    years_of_experience: 14,
    rating: 4.7,
    review_count: 42,
    featured: true,
    featured_review: 'Muy profesional, ágil y directo con la estrategia.',
  },
];
